import type {
  Partner,
  Agreement,
  Project,
  Expert,
  Activity,
  Achievement,
  SchoolInfo,
  Registration,
  DashboardStats,
} from './types'

// 学校基本信息
export const schoolInfo: SchoolInfo = {
  id: 'school-001',
  name: '华东职业技术学院',
  shortName: '华东职院',
  logo: '/placeholder.svg?height=80&width=80',
  type: '高等职业院校',
  province: '江苏省',
  city: '苏州市',
  address: '江苏省苏州市工业园区教育路188号',
  introduction: '华东职业技术学院是一所以工科为主，工、管、经、艺协调发展的全日制公办高等职业院校。学院始终坚持"产教融合、校企合作"的办学理念，积极探索校企深度合作模式，为区域经济发展培养高素质技术技能人才。',
  website: 'https://www.hdvtc.edu.cn',
  contactPhone: '0512-12345678',
  contactEmail: 'info@hdvtc.edu.cn',
  studentCount: 12000,
  teacherCount: 800,
  majorCount: 45,
  establishedYear: 1998,
}

// 合作主体数据
export const partners: Partner[] = [
  {
    id: 'p001',
    type: 'enterprise',
    name: '苏州智联科技有限公司',
    industry: '信息技术',
    region: '江苏省苏州市',
    description: '专注于人工智能和大数据解决方案的高新技术企业，是国家级专精特新"小巨人"企业。公司拥有多项核心技术专利，在智慧城市、智能制造等领域具有丰富的项目经验。',
    logo: '/placeholder.svg?height=64&width=64',
    status: 'active',
    rating: 'strategic',
    cooperationTypes: ['人才培养', '实习实训', '技术研发', '课程共建'],
    contactPerson: '张明',
    contactPhone: '13800138001',
    contactEmail: 'zhangming@zltech.com',
    address: '苏州市工业园区创业街100号',
    establishedYear: 2010,
    employeeCount: 500,
    createdAt: new Date('2022-01-15'),
    updatedAt: new Date('2024-06-20'),
  },
  {
    id: 'p002',
    type: 'enterprise',
    name: '江苏新能源集团',
    industry: '新能源',
    region: '江苏省南京市',
    description: '江苏省重点新能源企业，业务涵盖光伏发电、风力发电、储能系统等领域，是省内新能源行业的龙头企业。',
    logo: '/placeholder.svg?height=64&width=64',
    status: 'active',
    rating: 'deep',
    cooperationTypes: ['人才培养', '实习实训', '就业合作'],
    contactPerson: '李华',
    contactPhone: '13900139002',
    contactEmail: 'lihua@jsne.com',
    address: '南京市江北新区新能源大道88号',
    establishedYear: 2008,
    employeeCount: 2000,
    createdAt: new Date('2022-03-10'),
    updatedAt: new Date('2024-05-15'),
  },
  {
    id: 'p003',
    type: 'association',
    name: '苏州市人工智能行业协会',
    industry: '人工智能',
    region: '江苏省苏州市',
    description: '由苏州市工信局主管，汇聚全市人工智能领域企业、高校、研究机构的行业性社会组织，致力于推动AI产业发展。',
    logo: '/placeholder.svg?height=64&width=64',
    status: 'active',
    rating: 'strategic',
    cooperationTypes: ['产学研合作', '技能竞赛', '师资培训'],
    contactPerson: '王强',
    contactPhone: '13700137003',
    contactEmail: 'wangqiang@szaia.org',
    address: '苏州市姑苏区人民路200号',
    establishedYear: 2018,
    employeeCount: 30,
    createdAt: new Date('2022-05-20'),
    updatedAt: new Date('2024-04-10'),
  },
  {
    id: 'p004',
    type: 'park',
    name: '苏州工业园区人工智能产业园',
    industry: '人工智能',
    region: '江苏省苏州市',
    description: '国家级人工智能产业集聚区，入驻企业200余家，涵盖计算机视觉、自然语言处理、智能机器人等多个AI细分领域。',
    logo: '/placeholder.svg?height=64&width=64',
    status: 'active',
    rating: 'strategic',
    cooperationTypes: ['实习实训', '就业合作', '创新创业'],
    contactPerson: '陈伟',
    contactPhone: '13600136004',
    contactEmail: 'chenwei@sipaipark.com',
    address: '苏州工业园区AI产业园A座',
    establishedYear: 2019,
    employeeCount: 50,
    createdAt: new Date('2023-01-05'),
    updatedAt: new Date('2024-03-25'),
  },
  {
    id: 'p005',
    type: 'institution',
    name: '中国职业教育发展研究院',
    industry: '教育培训',
    region: '北京市',
    description: '国家级职业教育研究机构，承担职业教育政策研究、标准制定、质量评估等工作，在职业教育领域具有权威影响力。',
    logo: '/placeholder.svg?height=64&width=64',
    status: 'active',
    rating: 'deep',
    cooperationTypes: ['课程共建', '师资培训', '产学研合作'],
    contactPerson: '刘芳',
    contactPhone: '13500135005',
    contactEmail: 'liufang@cveri.org',
    address: '北京市海淀区学院路15号',
    establishedYear: 2005,
    employeeCount: 100,
    createdAt: new Date('2023-02-18'),
    updatedAt: new Date('2024-02-28'),
  },
  {
    id: 'p006',
    type: 'enterprise',
    name: '上海云智科技股份有限公司',
    industry: '信息技术',
    region: '上海市',
    description: '专注于云计算和企业数字化转型服务的上市公司，为各行业客户提供云平台建设、数据中心、IT运维等综合服务。',
    logo: '/placeholder.svg?height=64&width=64',
    status: 'active',
    rating: 'general',
    cooperationTypes: ['人才培养', '实习实训'],
    contactPerson: '赵磊',
    contactPhone: '13400134006',
    contactEmail: 'zhaolei@shyztech.com',
    address: '上海市浦东新区张江高科技园区',
    establishedYear: 2012,
    employeeCount: 800,
    createdAt: new Date('2023-06-10'),
    updatedAt: new Date('2024-01-20'),
  },
  {
    id: 'p007',
    type: 'enterprise',
    name: '杭州智能制造有限公司',
    industry: '智能制造',
    region: '浙江省杭州市',
    description: '专业从事工业机器人和智能生产线研发制造的国家高新技术企业，产品广泛应用于汽车、电子、家电等行业。',
    logo: '/placeholder.svg?height=64&width=64',
    status: 'negotiating',
    rating: 'general',
    cooperationTypes: ['人才培养', '技术研发'],
    contactPerson: '孙洁',
    contactPhone: '13300133007',
    contactEmail: 'sunjie@hzim.com',
    address: '杭州市余杭区智能制造产业园',
    establishedYear: 2015,
    employeeCount: 350,
    createdAt: new Date('2024-01-08'),
    updatedAt: new Date('2024-06-15'),
  },
  {
    id: 'p008',
    type: 'association',
    name: '长三角现代服务业联合会',
    industry: '现代物流',
    region: '上海市',
    description: '由长三角地区现代服务业企业自愿组成的跨区域行业组织，促进区域服务业协同发展和资源共享。',
    logo: '/placeholder.svg?height=64&width=64',
    status: 'active',
    rating: 'general',
    cooperationTypes: ['产学研合作', '社会服务'],
    contactPerson: '周丽',
    contactPhone: '13200132008',
    contactEmail: 'zhouli@csjmsba.org',
    address: '上海市黄浦区南京东路100号',
    establishedYear: 2016,
    employeeCount: 25,
    createdAt: new Date('2023-09-15'),
    updatedAt: new Date('2024-05-08'),
  },
]

// 合作协议数据
export const agreements: Agreement[] = [
  {
    id: 'a001',
    name: '战略合作框架协议',
    partnerId: 'p001',
    partnerName: '苏州智联科技有限公司',
    type: '战略合作协议',
    content: '双方建立长期战略合作伙伴关系，在人才培养、技术研发、产业服务等方面开展全面合作。',
    startDate: new Date('2022-03-01'),
    endDate: new Date('2027-02-28'),
    status: 'active',
    attachments: ['协议正文.pdf', '合作细则.pdf'],
    createdAt: new Date('2022-02-20'),
    updatedAt: new Date('2022-03-01'),
  },
  {
    id: 'a002',
    name: '产学研合作协议',
    partnerId: 'p001',
    partnerName: '苏州智联科技有限公司',
    type: '产学研合作协议',
    content: '共同开展人工智能应用技术研发，联合申报科研项目，共享知识产权成果。',
    startDate: new Date('2023-01-01'),
    endDate: new Date('2025-12-31'),
    status: 'active',
    createdAt: new Date('2022-12-15'),
    updatedAt: new Date('2023-01-01'),
  },
  {
    id: 'a003',
    name: '实习实训基地共建协议',
    partnerId: 'p002',
    partnerName: '江苏新能源集团',
    type: '实习实训协议',
    content: '在企业建立校外实习实训基地，每年接收学生实习不少于100人次。',
    startDate: new Date('2022-09-01'),
    endDate: new Date('2025-08-31'),
    status: 'active',
    createdAt: new Date('2022-08-10'),
    updatedAt: new Date('2022-09-01'),
  },
  {
    id: 'a004',
    name: '人才培养合作协议',
    partnerId: 'p003',
    partnerName: '苏州市人工智能行业协会',
    type: '人才培养协议',
    content: '共同制定人工智能专业人才培养方案，开展产业人才需求调研，组织技能竞赛活动。',
    startDate: new Date('2023-06-01'),
    endDate: new Date('2026-05-31'),
    status: 'active',
    createdAt: new Date('2023-05-15'),
    updatedAt: new Date('2023-06-01'),
  },
  {
    id: 'a005',
    name: '就业合作协议',
    partnerId: 'p004',
    partnerName: '苏州工业园区人工智能产业园',
    type: '就业合作协议',
    content: '建立毕业生就业推荐渠道，园区企业优先录用学院毕业生，每年提供就业岗位不少于50个。',
    startDate: new Date('2023-03-01'),
    endDate: new Date('2026-02-28'),
    status: 'active',
    createdAt: new Date('2023-02-20'),
    updatedAt: new Date('2023-03-01'),
  },
  {
    id: 'a006',
    name: '课程开发合作协议',
    partnerId: 'p005',
    partnerName: '中国职业教育发展研究院',
    type: '课程共建协议',
    content: '联合开发职业教育课程标准和教学资源，推动教学改革创新。',
    startDate: new Date('2023-09-01'),
    endDate: new Date('2025-08-31'),
    status: 'active',
    createdAt: new Date('2023-08-15'),
    updatedAt: new Date('2023-09-01'),
  },
]

// 合作项目数据
export const projects: Project[] = [
  {
    id: 'proj001',
    name: 'AI应用技术人才培养项目',
    partnerId: 'p001',
    partnerName: '苏州智联科技有限公司',
    type: '人才培养项目',
    agreementId: 'a001',
    phase: 'execution',
    description: '面向人工智能应用技术专业，校企共同制定人才培养方案，开发专业课程，建设实训环境，培养符合产业需求的高素质技术技能人才。',
    startDate: new Date('2023-03-01'),
    endDate: new Date('2025-06-30'),
    budget: 500000,
    milestones: [
      { id: 'm1', name: '需求调研', description: '完成企业岗位能力需求调研', dueDate: new Date('2023-04-30'), completedDate: new Date('2023-04-25'), status: 'completed' },
      { id: 'm2', name: '方案制定', description: '完成人才培养方案修订', dueDate: new Date('2023-06-30'), completedDate: new Date('2023-06-28'), status: 'completed' },
      { id: 'm3', name: '课程开发', description: '完成3门核心课程开发', dueDate: new Date('2024-02-28'), completedDate: new Date('2024-02-20'), status: 'completed' },
      { id: 'm4', name: '实训建设', description: '完成AI实训室建设', dueDate: new Date('2024-08-31'), status: 'in-progress' },
      { id: 'm5', name: '试点运行', description: '完成首届学生培养', dueDate: new Date('2025-06-30'), status: 'pending' },
    ],
    outputs: ['人才培养方案1套', 'AI应用课程3门', '实训项目库1个'],
    createdAt: new Date('2023-02-15'),
    updatedAt: new Date('2024-06-10'),
  },
  {
    id: 'proj002',
    name: '智能视觉检测技术研发项目',
    partnerId: 'p001',
    partnerName: '苏州智联科技有限公司',
    type: '技术研发项目',
    agreementId: 'a002',
    phase: 'execution',
    description: '联合开展基于深度学习的工业视觉检测技术研发，解决制造业质量检测中的技术难题。',
    startDate: new Date('2023-06-01'),
    endDate: new Date('2025-05-31'),
    budget: 800000,
    milestones: [
      { id: 'm1', name: '技术调研', description: '完成技术路线调研', dueDate: new Date('2023-08-31'), completedDate: new Date('2023-08-20'), status: 'completed' },
      { id: 'm2', name: '算法开发', description: '完成核心算法开发', dueDate: new Date('2024-06-30'), status: 'in-progress' },
      { id: 'm3', name: '系统集成', description: '完成检测系统集成', dueDate: new Date('2024-12-31'), status: 'pending' },
      { id: 'm4', name: '试点应用', description: '在合作企业试点应用', dueDate: new Date('2025-05-31'), status: 'pending' },
    ],
    outputs: ['技术报告', '软件著作权', '专利申请'],
    createdAt: new Date('2023-05-20'),
    updatedAt: new Date('2024-05-15'),
  },
  {
    id: 'proj003',
    name: '新能源技术实训基地建设',
    partnerId: 'p002',
    partnerName: '江苏新能源集团',
    type: '基地建设项目',
    agreementId: 'a003',
    phase: 'acceptance',
    description: '在企业建设校外实训基地，配备光伏发电、风电技术等实训设备，建立校企双导师制培养模式。',
    startDate: new Date('2022-09-01'),
    endDate: new Date('2024-08-31'),
    budget: 300000,
    milestones: [
      { id: 'm1', name: '方案设计', description: '完成基地建设方案', dueDate: new Date('2022-10-31'), completedDate: new Date('2022-10-25'), status: 'completed' },
      { id: 'm2', name: '设备采购', description: '完成实训设备采购', dueDate: new Date('2023-03-31'), completedDate: new Date('2023-03-20'), status: 'completed' },
      { id: 'm3', name: '基地建设', description: '完成基地建设', dueDate: new Date('2023-12-31'), completedDate: new Date('2023-12-28'), status: 'completed' },
      { id: 'm4', name: '验收运行', description: '完成验收并投入运行', dueDate: new Date('2024-06-30'), status: 'in-progress' },
    ],
    outputs: ['实训基地1个', '实训项目20个', '双师培养'],
    rating: 4.5,
    createdAt: new Date('2022-08-15'),
    updatedAt: new Date('2024-04-20'),
  },
  {
    id: 'proj004',
    name: 'AI技能竞赛项目',
    partnerId: 'p003',
    partnerName: '苏州市人工智能行业协会',
    type: '技能竞赛项目',
    agreementId: 'a004',
    phase: 'closure',
    description: '联合举办苏州市大学生人工智能应用技能竞赛，推动AI技术教学改革和人才培养质量提升。',
    startDate: new Date('2023-09-01'),
    endDate: new Date('2024-03-31'),
    budget: 100000,
    milestones: [
      { id: 'm1', name: '竞赛策划', description: '完成竞赛方案策划', dueDate: new Date('2023-10-15'), completedDate: new Date('2023-10-10'), status: 'completed' },
      { id: 'm2', name: '报名组织', description: '完成参赛队伍报名', dueDate: new Date('2023-11-30'), completedDate: new Date('2023-11-25'), status: 'completed' },
      { id: 'm3', name: '竞赛实施', description: '完成竞赛举办', dueDate: new Date('2024-01-15'), completedDate: new Date('2024-01-12'), status: 'completed' },
      { id: 'm4', name: '成果总结', description: '完成竞赛总结', dueDate: new Date('2024-03-31'), completedDate: new Date('2024-03-25'), status: 'completed' },
    ],
    outputs: ['获奖选手50名', '优秀作品20件'],
    rating: 4.8,
    createdAt: new Date('2023-08-20'),
    updatedAt: new Date('2024-04-01'),
  },
  {
    id: 'proj005',
    name: '创新创业孵化项目',
    partnerId: 'p004',
    partnerName: '苏州工业园区人工智能产业园',
    type: '创新创业项目',
    agreementId: 'a005',
    phase: 'execution',
    description: '依托产业园资源，建立大学生创新创业孵化平台，为学生创业团队提供场�����、资金、技术等支持。',
    startDate: new Date('2023-09-01'),
    endDate: new Date('2026-08-31'),
    budget: 200000,
    milestones: [
      { id: 'm1', name: '平台搭建', description: '完成孵化平台建设', dueDate: new Date('2024-03-31'), completedDate: new Date('2024-03-28'), status: 'completed' },
      { id: 'm2', name: '项目入驻', description: '首批10个项目入驻', dueDate: new Date('2024-09-30'), status: 'in-progress' },
      { id: 'm3', name: '孵化培育', description: '完成项目孵化培育', dueDate: new Date('2025-09-30'), status: 'pending' },
      { id: 'm4', name: '成果转化', description: '推动优秀项目注册公司', dueDate: new Date('2026-08-31'), status: 'pending' },
    ],
    outputs: ['孵化项目30个', '注册公司5家'],
    createdAt: new Date('2023-08-15'),
    updatedAt: new Date('2024-05-20'),
  },
]

// 专家数据
export const experts: Expert[] = [
  {
    id: 'e001',
    name: '张明',
    partnerId: 'p001',
    partnerName: '苏州智联科技有限公司',
    title: '技术总监',
    field: '人工智能',
    specialties: ['机器学习', '计算机视觉', '深度学习'],
    experience: 15,
    rating: 'gold',
    avatar: '/placeholder.svg?height=80&width=80',
    roles: ['产业导师', '技术顾问', '课程开发'],
    education: '清华大学计算机科学博士',
    achievements: ['发表SCI论文20余篇', '获得发明专利15项', '指导学生获省级竞赛一等奖'],
    contactEmail: 'zhangming@zltech.com',
    contactPhone: '13800138001',
    status: 'active',
    createdAt: new Date('2022-03-15'),
    updatedAt: new Date('2024-06-10'),
  },
  {
    id: 'e002',
    name: '李华',
    partnerId: 'p002',
    partnerName: '江苏新能源集团',
    title: '人力资源总监',
    field: '人力资源',
    specialties: ['人才管理', '企业培训', '职业规划'],
    experience: 12,
    rating: 'silver',
    avatar: '/placeholder.svg?height=80&width=80',
    roles: ['创业导师', '评审专家'],
    education: '南京大学工商管理硕士',
    achievements: ['省级人力资源管理师', '主持企业培训项目50余个'],
    contactEmail: 'lihua@jsne.com',
    contactPhone: '13900139002',
    status: 'active',
    createdAt: new Date('2022-09-20'),
    updatedAt: new Date('2024-05-15'),
  },
  {
    id: 'e003',
    name: '王强',
    partnerId: 'p003',
    partnerName: '苏州市人工智能行业协会',
    title: '秘书长',
    field: '企业管理',
    specialties: ['行业研究', '政策解读', '产业规划'],
    experience: 18,
    rating: 'gold',
    avatar: '/placeholder.svg?height=80&width=80',
    roles: ['客座教授', '产业导师'],
    education: '复旦大学管理学博士',
    achievements: ['参与制定省级AI产业发展规划', '发表行业研究报告10余份'],
    contactEmail: 'wangqiang@szaia.org',
    contactPhone: '13700137003',
    status: 'active',
    createdAt: new Date('2022-06-10'),
    updatedAt: new Date('2024-04-20'),
  },
  {
    id: 'e004',
    name: '陈伟',
    partnerId: 'p004',
    partnerName: '苏州工业园区人工智能产业园',
    title: '运营总监',
    field: '创新创业',
    specialties: ['创业孵化', '投融资', '商业模式'],
    experience: 10,
    rating: 'silver',
    avatar: '/placeholder.svg?height=80&width=80',
    roles: ['创业导师', '评审专家'],
    education: '上海交通大学MBA',
    achievements: ['孵化创业项目100余个', '指导企业融资总额超5亿'],
    contactEmail: 'chenwei@sipaipark.com',
    contactPhone: '13600136004',
    status: 'active',
    createdAt: new Date('2023-02-15'),
    updatedAt: new Date('2024-03-25'),
  },
  {
    id: 'e005',
    name: '刘芳',
    partnerId: 'p005',
    partnerName: '中国职业教育发展研究院',
    title: '研究员',
    field: '教育教学',
    specialties: ['职业教育', '课程开发', '教学改革'],
    experience: 20,
    rating: 'gold',
    avatar: '/placeholder.svg?height=80&width=80',
    roles: ['客座教授', '课程开发'],
    education: '北京师范大学教育学博士',
    achievements: ['主持国家级课题5项', '出版专著3部', '发表CSSCI论文30余篇'],
    contactEmail: 'liufang@cveri.org',
    contactPhone: '13500135005',
    status: 'active',
    createdAt: new Date('2023-03-10'),
    updatedAt: new Date('2024-02-28'),
  },
  {
    id: 'e006',
    name: '赵磊',
    partnerId: 'p006',
    partnerName: '上海云智科技股份有限公司',
    title: '架构师',
    field: '信息技术',
    specialties: ['云计算', '微服务', '系统架构'],
    experience: 8,
    rating: 'bronze',
    avatar: '/placeholder.svg?height=80&width=80',
    roles: ['技术顾问'],
    education: '浙江大学计算机硕士',
    achievements: ['AWS认证架构师', '主导企业上云项目20余个'],
    contactEmail: 'zhaolei@shyztech.com',
    contactPhone: '13400134006',
    status: 'active',
    createdAt: new Date('2023-07-20'),
    updatedAt: new Date('2024-01-20'),
  },
]

// 联盟活动数据
export const activities: Activity[] = [
  {
    id: 'act001',
    name: '2024年产教融合发展论坛',
    type: '研讨会',
    date: new Date('2024-09-15'),
    endDate: new Date('2024-09-16'),
    location: '华东职业技术学院学术报告厅',
    description: '邀请政府部门、行业企业、兄弟院校代表，共同研讨产教融合发展新模式、新路径，分享成功经验和典型案例。',
    status: 'published',
    maxParticipants: 200,
    currentParticipants: 156,
    organizer: '产教融合办公室',
    coverImage: '/placeholder.svg?height=200&width=400',
    createdAt: new Date('2024-07-01'),
    updatedAt: new Date('2024-08-15'),
  },
  {
    id: 'act002',
    name: '2024届毕业生校园招聘会',
    type: '招聘会',
    date: new Date('2024-10-20'),
    location: '学校体育馆',
    description: '联合50余家合作企业，为2024届毕业生提供就业岗位1000余个，涵盖信息技术、智能制造、新能源等领域。',
    status: 'published',
    maxParticipants: 500,
    currentParticipants: 320,
    organizer: '就业指导中心',
    coverImage: '/placeholder.svg?height=200&width=400',
    createdAt: new Date('2024-08-01'),
    updatedAt: new Date('2024-09-10'),
  },
  {
    id: 'act003',
    name: 'AI技术前沿专题讲座',
    type: '专题讲座',
    date: new Date('2024-08-28'),
    location: '信息工程学院阶梯教室',
    description: '邀请苏州智联科技技术总监张明博士，分享人工智能技术最新发展趋势和企业应用案例。',
    status: 'ended',
    maxParticipants: 150,
    currentParticipants: 142,
    organizer: '信息工程学院',
    coverImage: '/placeholder.svg?height=200&width=400',
    createdAt: new Date('2024-08-01'),
    updatedAt: new Date('2024-08-30'),
  },
  {
    id: 'act004',
    name: '校企合作签约仪式',
    type: '签约仪式',
    date: new Date('2024-11-08'),
    location: '学校行政楼贵宾厅',
    description: '与杭州智能制造有限公司举行战略合作协议签约仪式，开启智能制造领域深度合作。',
    status: 'published',
    maxParticipants: 50,
    currentParticipants: 35,
    organizer: '校企合作处',
    coverImage: '/placeholder.svg?height=200&width=400',
    createdAt: new Date('2024-09-15'),
    updatedAt: new Date('2024-10-01'),
  },
  {
    id: 'act005',
    name: '第三届大学生创新创业大赛',
    type: '技能竞赛',
    date: new Date('2024-12-01'),
    endDate: new Date('2024-12-03'),
    location: '创新创业学院',
    description: '联合苏州工业园区人工智能产业园举办，评选优秀创新创业项目，获奖项目将获得孵化支持。',
    status: 'draft',
    maxParticipants: 100,
    currentParticipants: 0,
    organizer: '创新创业学院',
    coverImage: '/placeholder.svg?height=200&width=400',
    createdAt: new Date('2024-09-20'),
    updatedAt: new Date('2024-09-20'),
  },
]

// 合作成果数据
export const achievements: Achievement[] = [
  {
    id: 'ach001',
    name: 'AI应用技术产业学院',
    type: 'joint-build',
    partnerId: 'p001',
    partnerName: '苏州智联科技有限公司',
    projectId: 'proj001',
    projectName: 'AI应用技术人才培养项目',
    description: '校企共建AI应用技术产业学院，整合双方资源优势，打造人才培养、技术研发、社会服务三位一体的产教融合平台。',
    images: ['/placeholder.svg?height=300&width=400', '/placeholder.svg?height=300&width=400'],
    publishDate: new Date('2024-03-15'),
    status: 'published',
    viewCount: 1256,
    createdAt: new Date('2024-03-10'),
    updatedAt: new Date('2024-06-20'),
  },
  {
    id: 'ach002',
    name: '新能源技术校外实训基地',
    type: 'training-base',
    partnerId: 'p002',
    partnerName: '江苏新能源集团',
    projectId: 'proj003',
    projectName: '新能源技术实训基地建设',
    description: '在江苏新能源集团建立校外实训基地，配备光伏发电、风电技术等实训设备，年接待实习学生200人次。',
    images: ['/placeholder.svg?height=300&width=400'],
    publishDate: new Date('2024-01-20'),
    status: 'published',
    viewCount: 856,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-05-10'),
  },
  {
    id: 'ach003',
    name: '人工智能应用技术专业教学标准',
    type: 'education-reform',
    partnerId: 'p005',
    partnerName: '中国职业教育发展研究院',
    description: '联合研制人工智能应用技术专业教学标准，已通过省级评审并在全省推广应用。',
    images: ['/placeholder.svg?height=300&width=400'],
    publishDate: new Date('2024-02-28'),
    status: 'published',
    viewCount: 2100,
    createdAt: new Date('2024-02-20'),
    updatedAt: new Date('2024-04-15'),
  },
  {
    id: 'ach004',
    name: '产教融合育人模式创新实践',
    type: 'case-study',
    partnerId: 'p001',
    partnerName: '苏州智联科技有限公司',
    description: '以AI应用技术产业学院建设为载体，探索形成"双主体、双导师、双证书"的产教融合育人模式，入选省级典型案例。',
    images: ['/placeholder.svg?height=300&width=400'],
    publishDate: new Date('2024-05-10'),
    status: 'published',
    viewCount: 1580,
    createdAt: new Date('2024-05-05'),
    updatedAt: new Date('2024-06-01'),
  },
  {
    id: 'ach005',
    name: '基于深度学习的工业视觉检测系统',
    type: 'patent',
    partnerId: 'p001',
    partnerName: '苏州智联科技有限公司',
    projectId: 'proj002',
    projectName: '智能视觉检测技术研发项目',
    description: '校企联合研发的工业视觉检测系统，已获得国家发明专利授权，并在合作企业实现产业化应用。',
    attachments: ['专利证书.pdf'],
    publishDate: new Date('2024-04-20'),
    status: 'published',
    viewCount: 920,
    createdAt: new Date('2024-04-15'),
    updatedAt: new Date('2024-05-20'),
  },
  {
    id: 'ach006',
    name: '省级产教融合实训基地',
    type: 'award',
    partnerId: 'p004',
    partnerName: '苏州工业园区人工智能产业园',
    description: '与苏州工业园区人工智能产业园共建的实训基地被评为省级产教融合实训基地，获得专项建设经费500万元。',
    images: ['/placeholder.svg?height=300&width=400'],
    publishDate: new Date('2024-06-15'),
    status: 'published',
    viewCount: 1820,
    createdAt: new Date('2024-06-10'),
    updatedAt: new Date('2024-07-01'),
  },
]

// 报名记录数据
export const registrations: Registration[] = [
  {
    id: 'reg001',
    activityId: 'act001',
    activityName: '2024年产教融合发展论坛',
    participantName: '张三',
    participantType: 'teacher',
    participantOrg: '华东职业技术学院',
    contactPhone: '13800000001',
    contactEmail: 'zhangsan@hdvtc.edu.cn',
    status: 'approved',
    registeredAt: new Date('2024-08-20'),
  },
  {
    id: 'reg002',
    activityId: 'act001',
    activityName: '2024年产教融合发展论坛',
    participantName: '李四',
    participantType: 'enterprise',
    participantOrg: '苏州智联科技有限公司',
    contactPhone: '13800000002',
    status: 'approved',
    registeredAt: new Date('2024-08-21'),
  },
  {
    id: 'reg003',
    activityId: 'act002',
    activityName: '2024届毕业生校园招聘会',
    participantName: '王五',
    participantType: 'student',
    participantOrg: '信息工程学院2024届',
    contactPhone: '13800000003',
    status: 'pending',
    registeredAt: new Date('2024-09-15'),
  },
]

// 仪表盘统计数据
export const dashboardStats: DashboardStats = {
  totalPartners: partners.length,
  activePartners: partners.filter(p => p.status === 'active').length,
  totalProjects: projects.length,
  activeProjects: projects.filter(p => p.phase === 'execution' || p.phase === 'initiation').length,
  totalAgreements: agreements.length,
  activeAgreements: agreements.filter(a => a.status === 'active').length,
  totalExperts: experts.length,
  totalActivities: activities.length,
  totalAchievements: achievements.filter(a => a.status === 'published').length,
  partnersByType: {
    enterprise: partners.filter(p => p.type === 'enterprise').length,
    association: partners.filter(p => p.type === 'association').length,
    park: partners.filter(p => p.type === 'park').length,
    institution: partners.filter(p => p.type === 'institution').length,
    expert: 0,
  },
  partnersByRating: {
    strategic: partners.filter(p => p.rating === 'strategic').length,
    deep: partners.filter(p => p.rating === 'deep').length,
    general: partners.filter(p => p.rating === 'general').length,
  },
  projectsByPhase: {
    initiation: projects.filter(p => p.phase === 'initiation').length,
    execution: projects.filter(p => p.phase === 'execution').length,
    acceptance: projects.filter(p => p.phase === 'acceptance').length,
    closure: projects.filter(p => p.phase === 'closure').length,
    archived: projects.filter(p => p.phase === 'archived').length,
    terminated: projects.filter(p => p.phase === 'terminated').length,
  },
}

// 辅助函数：根据ID获取数据
export function getPartnerById(id: string): Partner | undefined {
  return partners.find(p => p.id === id)
}

export function getAgreementById(id: string): Agreement | undefined {
  return agreements.find(a => a.id === id)
}

export function getProjectById(id: string): Project | undefined {
  return projects.find(p => p.id === id)
}

export function getExpertById(id: string): Expert | undefined {
  return experts.find(e => e.id === id)
}

export function getActivityById(id: string): Activity | undefined {
  return activities.find(a => a.id === id)
}

export function getAchievementById(id: string): Achievement | undefined {
  return achievements.find(a => a.id === id)
}

// 辅助函数：根据合作主体ID获取相关数据
export function getAgreementsByPartnerId(partnerId: string): Agreement[] {
  return agreements.filter(a => a.partnerId === partnerId)
}

export function getProjectsByPartnerId(partnerId: string): Project[] {
  return projects.filter(p => p.partnerId === partnerId)
}

export function getExpertsByPartnerId(partnerId: string): Expert[] {
  return experts.filter(e => e.partnerId === partnerId)
}

export function getAchievementsByPartnerId(partnerId: string): Achievement[] {
  return achievements.filter(a => a.partnerId === partnerId)
}

// ==================== 品牌运营管理数据 ====================

import type {
  TalentProfile,
  EmploymentCase,
  JobBrand,
  MajorBrand,
  TeacherBrand,
  CultureBrand,
  BrandTopic,
} from './types'

// 人才画像排名数据
export const talentProfiles: TalentProfile[] = [
  {
    id: 'tp001',
    studentId: 'S2021001',
    studentName: '陈思远',
    major: '人工智能应用技术',
    department: '信息工程学院',
    grade: '2021级',
    avatar: '/placeholder.svg?height=80&width=80',
    abilityScore: 95.5,
    certificationLevel: '高级',
    taskCompletionRate: 98,
    comprehensiveRank: 1,
    abilityTags: ['机器学习', '深度学习', 'Python', '数据分析'],
    employmentStatus: 'employed',
    employmentCompany: '苏州智联科技有限公司',
    employmentPosition: 'AI算法工程师',
    isFeatured: true,
    updatedAt: new Date('2024-06-15'),
  },
  {
    id: 'tp002',
    studentId: 'S2021015',
    studentName: '王雨涵',
    major: '软件技术',
    department: '信息工程学院',
    grade: '2021级',
    avatar: '/placeholder.svg?height=80&width=80',
    abilityScore: 93.2,
    certificationLevel: '高级',
    taskCompletionRate: 96,
    comprehensiveRank: 2,
    abilityTags: ['Java', '微服务', '数据库', '云计算'],
    employmentStatus: 'employed',
    employmentCompany: '上海云智科技股份有限公司',
    employmentPosition: '后端开发工程师',
    isFeatured: true,
    updatedAt: new Date('2024-06-10'),
  },
  {
    id: 'tp003',
    studentId: 'S2021028',
    studentName: '李明轩',
    major: '新能源技术',
    department: '新能源学院',
    grade: '2021级',
    avatar: '/placeholder.svg?height=80&width=80',
    abilityScore: 91.8,
    certificationLevel: '中级',
    taskCompletionRate: 94,
    comprehensiveRank: 3,
    abilityTags: ['光伏技术', '电力系统', '储能技术'],
    employmentStatus: 'employed',
    employmentCompany: '江苏新能源集团',
    employmentPosition: '技术员',
    isFeatured: true,
    updatedAt: new Date('2024-06-08'),
  },
  {
    id: 'tp004',
    studentId: 'S2022003',
    studentName: '张佳琪',
    major: '人工智能应用技术',
    department: '信息工程学院',
    grade: '2022级',
    avatar: '/placeholder.svg?height=80&width=80',
    abilityScore: 90.5,
    certificationLevel: '中级',
    taskCompletionRate: 92,
    comprehensiveRank: 4,
    abilityTags: ['计算机视觉', 'PyTorch', '图像处理'],
    employmentStatus: 'seeking',
    isFeatured: false,
    updatedAt: new Date('2024-06-05'),
  },
  {
    id: 'tp005',
    studentId: 'S2022010',
    studentName: '刘子豪',
    major: '智能制造技术',
    department: '机械工程学院',
    grade: '2022级',
    avatar: '/placeholder.svg?height=80&width=80',
    abilityScore: 89.3,
    certificationLevel: '中级',
    taskCompletionRate: 91,
    comprehensiveRank: 5,
    abilityTags: ['工业机器人', 'PLC编程', '自动化控制'],
    employmentStatus: 'studying',
    isFeatured: false,
    updatedAt: new Date('2024-06-01'),
  },
]

// 典型就业案例数据
export const employmentCases: EmploymentCase[] = [
  {
    id: 'ec001',
    studentName: '陈思远',
    major: '人工智能应用技术',
    graduationYear: 2024,
    company: '苏州智联科技有限公司',
    companyLogo: '/placeholder.svg?height=64&width=64',
    position: 'AI算法工程师',
    salary: '15-20K',
    abilityTags: ['机器学习', '深度学习', 'Python'],
    story: '在校期间积极参与校企合作项目，在苏州智联科技实习期间表现优异，毕业后顺利转正。目前负责公司计算机视觉算法的研发工作，已独立完成多个项目交付。',
    photo: '/placeholder.svg?height=200&width=200',
    status: 'published',
    viewCount: 1580,
    createdAt: new Date('2024-04-15'),
    updatedAt: new Date('2024-06-20'),
  },
  {
    id: 'ec002',
    studentName: '王雨涵',
    major: '软件技术',
    graduationYear: 2024,
    company: '上海云智科技股份有限公司',
    companyLogo: '/placeholder.svg?height=64&width=64',
    position: '后端开发工程师',
    salary: '12-18K',
    abilityTags: ['Java', '微服务', 'Spring Boot'],
    story: '通过学校推荐参加企业招聘会，凭借扎实的专业技能和项目经验脱颖而出。入职后快速适应工作节奏，已晋升为团队技术骨干。',
    photo: '/placeholder.svg?height=200&width=200',
    status: 'published',
    viewCount: 1245,
    createdAt: new Date('2024-04-20'),
    updatedAt: new Date('2024-06-15'),
  },
  {
    id: 'ec003',
    studentName: '李明轩',
    major: '新能源技术',
    graduationYear: 2024,
    company: '江苏新能源集团',
    companyLogo: '/placeholder.svg?height=64&width=64',
    position: '技术员',
    salary: '10-15K',
    abilityTags: ['光伏技术', '电力系统', '设备维护'],
    story: '在校期间多次到江苏新能源集团实训基地学习，掌握了光伏电站运维的核心技能。毕业后入职该公司，从事光伏电站的技术运维工作。',
    photo: '/placeholder.svg?height=200&width=200',
    status: 'published',
    viewCount: 980,
    createdAt: new Date('2024-05-01'),
    updatedAt: new Date('2024-06-10'),
  },
]

// 岗位品牌数据
export const jobBrands: JobBrand[] = [
  {
    id: 'jb001',
    name: 'AI算法工程师',
    industry: '人工智能',
    level: 'recommended',
    description: '负责人工智能算法的研发与优化，包括机器学习、深度学习、计算机视觉等领域的技术攻关和项目落地。',
    abilityModel: ['Python编程', '机器学习算法', '深度学习框架', '数据处理', '模型优化'],
    suitableMajors: ['人工智能应用技术', '软件技术', '大数据技术'],
    averageSalary: '15-25K',
    demandCount: 156,
    featureTags: ['高薪岗位', '技术前沿', '发展空间大'],
    coverImage: '/placeholder.svg?height=200&width=300',
    status: 'published',
    viewCount: 3250,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-06-20'),
  },
  {
    id: 'jb002',
    name: '全栈开发工程师',
    industry: '信息技术',
    level: 'key',
    description: '负责Web应用的前后端开发，具备独立完成项目开发的能力，熟悉主流技术栈和开发流程。',
    abilityModel: ['前端开发', '后端开发', '数据库', '系统设计', '项目管理'],
    suitableMajors: ['软件技术', '计算机应用技术', '人工智能应用技术'],
    averageSalary: '12-20K',
    demandCount: 245,
    featureTags: ['需求量大', '技术全面', '远程友好'],
    coverImage: '/placeholder.svg?height=200&width=300',
    status: 'published',
    viewCount: 2890,
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-06-15'),
  },
  {
    id: 'jb003',
    name: '工业机器人工程师',
    industry: '智能制造',
    level: 'recommended',
    description: '负责工业机器人的编程调试、系统集成和技术支持，参与自动化生产线的设计与优化。',
    abilityModel: ['机器人编程', 'PLC控制', '机械设计', '电气调试', '现场实施'],
    suitableMajors: ['智能制造技术', '机电一体化', '工业机器人技术'],
    averageSalary: '10-18K',
    demandCount: 128,
    featureTags: ['制造升级', '实操性强', '稳定就业'],
    coverImage: '/placeholder.svg?height=200&width=300',
    status: 'published',
    viewCount: 1950,
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-06-10'),
  },
  {
    id: 'jb004',
    name: '新能源技术员',
    industry: '新能源',
    level: 'key',
    description: '负责光伏/风电设备的安装、调试、运维和故障处理，确保新能源发电系统的稳定运行。',
    abilityModel: ['电力系统', '设备运维', '故障诊断', '安全规范', '数据监控'],
    suitableMajors: ['新能源技术', '电气自动化', '光伏发电技术'],
    averageSalary: '8-15K',
    demandCount: 98,
    featureTags: ['绿色产业', '政策支持', '前景广阔'],
    coverImage: '/placeholder.svg?height=200&width=300',
    status: 'published',
    viewCount: 1520,
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2024-06-05'),
  },
]

// 专业品牌数据
export const majorBrands: MajorBrand[] = [
  {
    id: 'mb001',
    name: '人工智能应用技术',
    department: '信息工程学院',
    level: 'recommended',
    introduction: '本专业培养具备人工智能基础理论和应用开发能力的高素质技术技能人才，是省级特色专业和教育部1+X证书制度试点专业。',
    cultivationGoal: '培养掌握人工智能基础理论，具备机器学习、深度学习、计算机视觉等AI应用开发能力的技术技能人才。',
    coreCourses: ['Python程序设计', '机器学习基础', '深度学习应用', '计算机视觉', '自然语言处理'],
    employmentDirections: ['AI算法工程师', '数据分析师', '机器学习工程师', '智能应用开发'],
    cooperationPartners: ['苏州智联科技有限公司', '苏州市人工智能行业协会'],
    featuredAchievements: ['省级特色专业', '教育部1+X试点', '省技能竞赛一等奖'],
    studentCount: 320,
    employmentRate: 98.5,
    coverImage: '/placeholder.svg?height=300&width=500',
    status: 'published',
    viewCount: 4560,
    createdAt: new Date('2023-09-01'),
    updatedAt: new Date('2024-06-20'),
  },
  {
    id: 'mb002',
    name: '软件技术',
    department: '信息工程学院',
    level: 'key',
    introduction: '本专业是学校传统优势专业，面向软件开发行业培养全栈开发人才，与多家知名企业建立深度合作关系。',
    cultivationGoal: '培养具备软件开发全流程能力，能够独立完成Web应用、移动应用开发的技术技能人才。',
    coreCourses: ['Java程序设计', 'Web前端开发', '数据库技术', '软件工程', '微服务架构'],
    employmentDirections: ['Java开发工程师', '前端开发工程师', '全栈开发工程师', '软件测试工程师'],
    cooperationPartners: ['上海云智科技股份有限公司'],
    featuredAchievements: ['校级重点专业', '华为ICT学院共建'],
    studentCount: 450,
    employmentRate: 97.2,
    coverImage: '/placeholder.svg?height=300&width=500',
    status: 'published',
    viewCount: 3890,
    createdAt: new Date('2023-09-01'),
    updatedAt: new Date('2024-06-15'),
  },
  {
    id: 'mb003',
    name: '新能源技术',
    department: '新能源学院',
    level: 'key',
    introduction: '本专业聚焦光伏发电、风力发电等新能源领域，与省内多家新能源龙头企业建立校企合作关系。',
    cultivationGoal: '培养掌握新能源发电技术，具备设备安装调试、运行维护能力的技术技能人才。',
    coreCourses: ['光伏发电技术', '风力发电技术', '电力电子技术', '新能源系统设计', '储能技术'],
    employmentDirections: ['新能源技术员', '光伏运维工程师', '电站调度员', '设备管理员'],
    cooperationPartners: ['江苏新能源集团'],
    featuredAchievements: ['省级骨干专业', '校外实训基地'],
    studentCount: 280,
    employmentRate: 96.8,
    coverImage: '/placeholder.svg?height=300&width=500',
    status: 'published',
    viewCount: 2450,
    createdAt: new Date('2023-09-01'),
    updatedAt: new Date('2024-06-10'),
  },
  {
    id: 'mb004',
    name: '智能制造技术',
    department: '机械工程学院',
    level: 'standard',
    introduction: '本专业面向智能制造产业，培养掌握工业机器人、数控技术、自动化控制等核心技能的高素质人才。',
    cultivationGoal: '培养具备智能制造系统集成、工业机器人应用、自动化生产线运维能力的技术技能人才。',
    coreCourses: ['工业机器人技术', 'PLC编程与应用', '数控加工技术', '自动化生产线', '智能制造系统'],
    employmentDirections: ['工业机器人工程师', '自动化工程师', '数控编程员', '设备维护工程师'],
    cooperationPartners: ['杭州智能制造有限公司', '苏州工业园区人工智能产业园'],
    featuredAchievements: ['校企共建实训室'],
    studentCount: 200,
    employmentRate: 95.5,
    coverImage: '/placeholder.svg?height=300&width=500',
    status: 'published',
    viewCount: 1890,
    createdAt: new Date('2023-09-01'),
    updatedAt: new Date('2024-06-05'),
  },
]

// 师资品牌数据
export const teacherBrands: TeacherBrand[] = [
  {
    id: 'tb001',
    name: '李教授',
    department: '信息工程学院',
    title: '教授',
    type: 'teaching-master',
    avatar: '/placeholder.svg?height=120&width=120',
    introduction: '省级教学名师，长期从事人工智能教学与科研工作，主持多项省部级科研项目，是学校AI专业带头人。',
    researchFields: ['人工智能', '机器学习', '计算机视觉'],
    achievements: ['主持省级课题3项', '发表SCI论文15篇', '指导学生获国赛一等奖'],
    courses: ['机器学习基础', '深度学习应用', 'Python程序设计'],
    awards: ['省级教学名师', '省科技进步二等奖', '校优秀教师'],
    isFeatured: true,
    status: 'published',
    viewCount: 2340,
    createdAt: new Date('2023-06-01'),
    updatedAt: new Date('2024-06-20'),
  },
  {
    id: 'tb002',
    name: '王副教授',
    department: '信息工程学院',
    title: '副教授',
    type: 'dual-qualified',
    avatar: '/placeholder.svg?height=120&width=120',
    introduction: '双师型教师，曾在知名IT企业工作8年，具有丰富的项目开发经验，现负责校企合作项目的技术对接工作。',
    researchFields: ['软件工程', 'Web开发', '微服务架构'],
    achievements: ['企业项目经验丰富', '软件著作权5项', '指导学生就业率100%'],
    courses: ['Java程序设计', 'Web前端开发', '软件项目管理'],
    awards: ['双师型教师', '校教学能手', '优秀班主任'],
    isFeatured: true,
    status: 'published',
    viewCount: 1890,
    createdAt: new Date('2023-06-15'),
    updatedAt: new Date('2024-06-15'),
  },
  {
    id: 'tb003',
    name: '张讲师',
    department: '新能源学院',
    title: '讲师',
    type: 'backbone',
    avatar: '/placeholder.svg?height=120&width=120',
    introduction: '骨干教师，新能源技术专业核心课程负责人，与江苏新能源集团深度合作，负责实训基地课程开发。',
    researchFields: ['光伏技术', '储能技术', '新能源系统'],
    achievements: ['参与企业横向课题2项', '开发实训项目10个', '编写校本教材2部'],
    courses: ['光伏发电技术', '储能技术', '新能源系统设计'],
    awards: ['校骨干教师', '校青年教学新秀'],
    isFeatured: false,
    status: 'published',
    viewCount: 1250,
    createdAt: new Date('2023-07-01'),
    updatedAt: new Date('2024-06-10'),
  },
  {
    id: 'tb004',
    name: '刘副教授',
    department: '机械工程学院',
    title: '副教授',
    type: 'award-winning',
    avatar: '/placeholder.svg?height=120&width=120',
    introduction: '获奖教师，在全国职业院校教学能力大赛中获一等奖，专注于智能制造领域的教学改革与创新。',
    researchFields: ['工业机器人', '智能制造', '自动化控制'],
    achievements: ['全国教学能力大赛一等奖', '主持教改项目3项', '发明专利2项'],
    courses: ['工业机器人技术', 'PLC编程与应用', '自动化生产线'],
    awards: ['全国教学能力大赛一等奖', '省级教学成果二等奖'],
    isFeatured: true,
    status: 'published',
    viewCount: 1680,
    createdAt: new Date('2023-07-15'),
    updatedAt: new Date('2024-06-05'),
  },
]

// 文化思政品牌数据
export const cultureBrands: CultureBrand[] = [
  {
    id: 'cb001',
    name: '工匠精神进课堂',
    type: 'case',
    description: '将工匠精神融入专业课程教学，邀请企业技能大师分享成长经历，培养学生精益求精的职业素养。',
    content: '��校邀请来自合作企业的省级技能大师走进课堂，通过亲身经历分享、现场技能演示等方式，让学生深刻理解工匠精神的内涵。同时，在专业课程中融入工匠精神教育元素，引导学生树立正确的职业观念。',
    images: ['/placeholder.svg?height=300&width=400'],
    coverImage: '/placeholder.svg?height=200&width=300',
    status: 'published',
    viewCount: 1560,
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-06-20'),
  },
  {
    id: 'cb002',
    name: '职业道德教育实践',
    type: 'resource',
    description: '开发职业道德教育资源库，包括案例、视频、测评等多种形式，支撑专业课程思政建设。',
    content: '建设包含100个职业道德案例、50个微课视频、20套测评试题的资源库，覆盖信息技术、智能制造、新能源等专业领域，支持教师在专业课程中融入思政元素。',
    images: ['/placeholder.svg?height=300&width=400'],
    coverImage: '/placeholder.svg?height=200&width=300',
    relatedMajor: '全校通用',
    status: 'published',
    viewCount: 980,
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2024-06-15'),
  },
  {
    id: 'cb003',
    name: '校园科技文化节',
    type: 'activity',
    description: '每年举办校园科技文化节，展示学生创新创业成果，弘扬科技创新文化。',
    content: '第十届校园科技文化节圆满落幕，共展出学生科技作品200余件，举办学术讲座20场，吸引校内外参观者5000余人次。活动有效营造了崇尚科学、追求创新的校园文化氛围。',
    images: ['/placeholder.svg?height=300&width=400', '/placeholder.svg?height=300&width=400'],
    coverImage: '/placeholder.svg?height=200&width=300',
    status: 'published',
    viewCount: 2350,
    createdAt: new Date('2024-05-01'),
    updatedAt: new Date('2024-06-10'),
  },
  {
    id: 'cb004',
    name: '课程思政示范课',
    type: 'award',
    description: '《人工智能伦理与社会》获评省级课程思政示范课，探索AI专业课程思政建设新路径。',
    content: '该课程将人工智能伦理、社会责任、职业道德等思政元素有机融入AI专业知识教学，引导学生思考技术发展与社会进步的关系，培养学生的社会责任感。课程获评2024年省级课程思政示范课。',
    images: ['/placeholder.svg?height=300&width=400'],
    coverImage: '/placeholder.svg?height=200&width=300',
    relatedMajor: '人工智能应用技术',
    status: 'published',
    viewCount: 1120,
    createdAt: new Date('2024-04-15'),
    updatedAt: new Date('2024-06-05'),
  },
]

// 品牌专题页数据
export const brandTopics: BrandTopic[] = [
  {
    id: 'bt001',
    name: '2024届优秀毕业生风采',
    theme: '人才培养',
    description: '展示2024届优秀毕业生的成长历程和就业成果，彰显学校人才培养质量。',
    coverImage: '/placeholder.svg?height=400&width=800',
    layout: 'magazine',
    content: [
      { type: 'text', title: '前言', content: '2024届毕业生在校期间表现优异，在技能竞赛、创新创业、就业创业等方面取得了丰硕成果...' },
      { type: 'image', content: '/placeholder.svg?height=300&width=500' },
    ],
    relatedBrands: [
      { type: 'talent', ids: ['tp001', 'tp002', 'tp003'] },
    ],
    isRecommended: true,
    status: 'published',
    viewCount: 3560,
    createdAt: new Date('2024-06-01'),
    updatedAt: new Date('2024-06-20'),
  },
  {
    id: 'bt002',
    name: '产教融合成果巡礼',
    theme: '校企合作',
    description: '回顾学校产教融合发展历程，展示校企合作的丰硕成果。',
    coverImage: '/placeholder.svg?height=400&width=800',
    layout: 'timeline',
    content: [
      { type: 'text', title: '发展历程', content: '近年来，学校积极探索产教融合新模式，与行业龙头企业建立深度合作关系...' },
    ],
    relatedBrands: [
      { type: 'partner', ids: ['p001', 'p002', 'p003'] },
    ],
    isRecommended: true,
    status: 'published',
    viewCount: 2890,
    createdAt: new Date('2024-05-15'),
    updatedAt: new Date('2024-06-15'),
  },
]

// 辅助函数：获取品牌数据
export function getTalentProfileById(id: string): TalentProfile | undefined {
  return talentProfiles.find(t => t.id === id)
}

export function getEmploymentCaseById(id: string): EmploymentCase | undefined {
  return employmentCases.find(e => e.id === id)
}

export function getJobBrandById(id: string): JobBrand | undefined {
  return jobBrands.find(j => j.id === id)
}

export function getMajorBrandById(id: string): MajorBrand | undefined {
  return majorBrands.find(m => m.id === id)
}

export function getTeacherBrandById(id: string): TeacherBrand | undefined {
  return teacherBrands.find(t => t.id === id)
}

export function getCultureBrandById(id: string): CultureBrand | undefined {
  return cultureBrands.find(c => c.id === id)
}

export function getBrandTopicById(id: string): BrandTopic | undefined {
  return brandTopics.find(b => b.id === id)
}

// ==================== 就业服务管理数据 ====================

import type {
  Job,
  StudentProfile,
  JobApplication,
  EmploymentStats,
} from './types'

// 岗位数据
export const jobs: Job[] = [
  {
    id: 'job001',
    title: 'AI算法工程师',
    partnerId: 'p001',
    partnerName: '苏州智联科技有限公司',
    partnerLogo: '/placeholder.svg?height=64&width=64',
    type: 'full-time',
    workNature: 'on-site',
    department: '算法研发部',
    location: '江苏省苏州市工业园区',
    salaryMin: 15000,
    salaryMax: 25000,
    salaryUnit: 'month',
    requirements: [
      '计算机、人工智能、数学等相关专业本科及以上学历',
      '熟悉Python、TensorFlow/PyTorch等深度学习框架',
      '了解机器学习、深度学习基本原理',
      '有实际项目经验者优先',
    ],
    responsibilities: [
      '负责AI算法的研发与优化',
      '参与计算机视觉、NLP等方向的技术攻关',
      '完成算法模型的训练、测试和部署',
      '撰写技术文档和专利申请',
    ],
    benefits: ['五险一金', '年终奖金', '带薪年假', '定期体检', '技术培训'],
    education: '本科',
    experience: '应届生',
    headcount: 5,
    suitableMajors: ['人工智能应用技术', '软件技术', '大数据技术'],
    skills: ['Python', '机器学习', '深度学习', 'TensorFlow', 'PyTorch'],
    description: '加入我们的AI研发团队，参与前沿人工智能技术的研发工作。我们提供完善的培训体系和广阔的发展空间，期待有志于AI领域的优秀人才加入。',
    contactPerson: '张HR',
    contactPhone: '13800138001',
    contactEmail: 'hr@zltech.com',
    status: 'published',
    isUrgent: true,
    isRecommended: true,
    viewCount: 1580,
    applicationCount: 45,
    deadline: new Date('2024-12-31'),
    createdAt: new Date('2024-06-01'),
    updatedAt: new Date('2024-06-20'),
  },
  {
    id: 'job002',
    title: 'Java开发工程师',
    partnerId: 'p001',
    partnerName: '苏州智联科技有限公司',
    partnerLogo: '/placeholder.svg?height=64&width=64',
    type: 'full-time',
    workNature: 'on-site',
    department: '软件开发部',
    location: '江苏省苏州市工业园区',
    salaryMin: 12000,
    salaryMax: 20000,
    salaryUnit: 'month',
    requirements: [
      '计算机相关专业大专及以上学历',
      '熟悉Java语言，了解Spring Boot框架',
      '熟悉MySQL等关系型数据库',
      '有良好的编码习惯和团队协作能力',
    ],
    responsibilities: [
      '参与企业级应用系统的开发与维护',
      '根据需求文档完成功能模块的设计与开发',
      '编写单元测试，确保代码质量',
      '参与代码评审和技术分享',
    ],
    benefits: ['五险一金', '年终奖金', '带薪年假', '免费午餐'],
    education: '大专',
    experience: '应届生',
    headcount: 8,
    suitableMajors: ['软件技术', '计算机应用技术', '人工智能应用技术'],
    skills: ['Java', 'Spring Boot', 'MySQL', 'Redis', 'Git'],
    description: '我们正在寻找热爱编程、愿意学习的Java开发工程师。公司提供完善的mentor制度，帮助新人快速成长。',
    contactPerson: '李HR',
    contactPhone: '13800138002',
    contactEmail: 'hr@zltech.com',
    status: 'published',
    isUrgent: false,
    isRecommended: true,
    viewCount: 2340,
    applicationCount: 78,
    deadline: new Date('2024-12-31'),
    createdAt: new Date('2024-06-05'),
    updatedAt: new Date('2024-06-18'),
  },
  {
    id: 'job003',
    title: '新能源技术实习生',
    partnerId: 'p002',
    partnerName: '江苏新能源集团',
    partnerLogo: '/placeholder.svg?height=64&width=64',
    type: 'internship',
    workNature: 'on-site',
    department: '技术运维部',
    location: '江苏省南京市江北新区',
    salaryMin: 3000,
    salaryMax: 4000,
    salaryUnit: 'month',
    requirements: [
      '新能源、电气自动化等相关专业在读学生',
      '能够全职实习3个月以上',
      '有责任心，学习能力强',
      '能适应户外工作环境',
    ],
    responsibilities: [
      '协助工程师进行光伏电站的日常巡检',
      '学习光伏设备的运维知识',
      '整理技术资料和运维记录',
      '参与设备故障的分析和处理',
    ],
    benefits: ['实习补贴', '免费住宿', '免费班车', '转正机会'],
    education: '大专',
    experience: '在校生',
    headcount: 10,
    suitableMajors: ['新能源技术', '电气自动化', '光伏发电技术'],
    skills: ['电力系统基础', '设备运维', 'Office办公软件'],
    description: '实习期间表现优秀者可获得毕业后转正机会，成为公司正式员工。',
    contactPerson: '王主管',
    contactPhone: '13900139002',
    contactEmail: 'hr@jsne.com',
    status: 'published',
    isUrgent: true,
    isRecommended: false,
    viewCount: 890,
    applicationCount: 32,
    deadline: new Date('2024-09-30'),
    createdAt: new Date('2024-06-10'),
    updatedAt: new Date('2024-06-15'),
  },
  {
    id: 'job004',
    title: '前端开发工程师',
    partnerId: 'p001',
    partnerName: '苏州智联科技有限公司',
    partnerLogo: '/placeholder.svg?height=64&width=64',
    type: 'full-time',
    workNature: 'hybrid',
    department: '前端开发部',
    location: '江苏省苏州市工业园区',
    salaryMin: 10000,
    salaryMax: 18000,
    salaryUnit: 'month',
    requirements: [
      '计算机相关专业大专及以上学历',
      '熟悉HTML/CSS/JavaScript',
      '熟悉Vue或React框架',
      '有移动端开发经验者优先',
    ],
    responsibilities: [
      '负责公司产品的前端页面开发',
      '与UI设计师协作完成页面还原',
      '优化前端性能，提升用户体验',
      '参与技术选型和架构设计',
    ],
    benefits: ['五险一金', '弹性工作', '远程办公', '技术分享'],
    education: '大专',
    experience: '1年以下',
    headcount: 3,
    suitableMajors: ['软件技术', '计算机应用技术'],
    skills: ['JavaScript', 'Vue', 'React', 'CSS', 'TypeScript'],
    description: '加入我们的前端团队，参与ToB和ToC产品的开发。公司技术氛围浓厚，定期组织技术分享和培训。',
    contactPerson: '张HR',
    contactPhone: '13800138001',
    contactEmail: 'hr@zltech.com',
    status: 'published',
    isUrgent: false,
    isRecommended: true,
    viewCount: 1120,
    applicationCount: 28,
    deadline: new Date('2024-12-31'),
    createdAt: new Date('2024-06-12'),
    updatedAt: new Date('2024-06-20'),
  },
  {
    id: 'job005',
    title: '工业机器人操作员',
    partnerId: 'p006',
    partnerName: '杭州智能制造有限公司',
    partnerLogo: '/placeholder.svg?height=64&width=64',
    type: 'full-time',
    workNature: 'on-site',
    department: '生产车间',
    location: '浙江省杭州市萧山区',
    salaryMin: 8000,
    salaryMax: 12000,
    salaryUnit: 'month',
    requirements: [
      '机电一体化、工业机器人等相关专业',
      '熟悉工业机器人的基本操作',
      '有PLC编程基础者优先',
      '能适应倒班工作制',
    ],
    responsibilities: [
      '负责工业机器人的日常操作和维护',
      '进行机器人程序的调试和优化',
      '配合完成自动化产线的升级改造',
      '记录设备运行数据，编写运维报告',
    ],
    benefits: ['五险一金', '包吃包住', '加班补贴', '技能补贴'],
    education: '中专/中技',
    experience: '应届生',
    headcount: 15,
    suitableMajors: ['智能制造技术', '工业机器人技术', '机电一体化'],
    skills: ['工业机器人操作', 'PLC编程', '机械基础', '电气基础'],
    description: '公司提供系统的技术培训，帮助员工快速掌握工业机器人操作技能。优秀员工可晋升为技术主管。',
    contactPerson: '陈经理',
    contactPhone: '13600136005',
    contactEmail: 'hr@hzim.com',
    status: 'published',
    isUrgent: true,
    isRecommended: false,
    viewCount: 650,
    applicationCount: 18,
    deadline: new Date('2024-11-30'),
    createdAt: new Date('2024-06-15'),
    updatedAt: new Date('2024-06-20'),
  },
  {
    id: 'job006',
    title: '数据分析师',
    partnerId: 'p001',
    partnerName: '苏州智联科技有限公司',
    partnerLogo: '/placeholder.svg?height=64&width=64',
    type: 'full-time',
    workNature: 'on-site',
    department: '数据中心',
    location: '江苏省苏州市工业园区',
    salaryMin: 10000,
    salaryMax: 16000,
    salaryUnit: 'month',
    requirements: [
      '统计学、数学、计算机等相关专业本科及以上学历',
      '熟悉SQL，有数据库操作经验',
      '熟练使用Excel、Python进行数据分析',
      '有数据可视化工具使用经验者优先',
    ],
    responsibilities: [
      '收集、整理和分析业务数据',
      '制作数据报表和可视化图表',
      '发现数据中的业务问题和机会',
      '为业务决策提供数据支持',
    ],
    benefits: ['五险一金', '年终奖金', '带薪年假', '节日福利'],
    education: '本科',
    experience: '应届生',
    headcount: 2,
    suitableMajors: ['大数据技术', '软件技术', '人工智能应用技术'],
    skills: ['SQL', 'Python', 'Excel', '数据可视化', '统计分析'],
    description: '加入数据团队，用数据驱动业务增长。我们提供专业的数据分析培训和职业发展通道。',
    contactPerson: '张HR',
    contactPhone: '13800138001',
    contactEmail: 'hr@zltech.com',
    status: 'published',
    isUrgent: false,
    isRecommended: true,
    viewCount: 980,
    applicationCount: 35,
    deadline: new Date('2024-12-31'),
    createdAt: new Date('2024-06-18'),
    updatedAt: new Date('2024-06-20'),
  },
]

// 学生档案数据
export const studentProfiles: StudentProfile[] = [
  {
    id: 'stu001',
    name: '陈思远',
    gender: 'male',
    avatar: '/placeholder.svg?height=80&width=80',
    major: '人工智能应用技术',
    department: '信息工程学院',
    grade: '2021级',
    studentId: 'S2021001',
    phone: '13812345001',
    email: 'chensiyuan@student.hdvtc.edu.cn',
    expectedSalary: '15-20K',
    expectedLocation: '苏州、上海',
    skills: ['Python', '机器学习', '深度学习', 'TensorFlow'],
    certificates: ['计算机等级证书', '英语四级', 'AI开发者认证'],
    internshipExperience: '曾在苏州智联科技实习3个月，参与计算机视觉项目开发',
    selfIntroduction: '我是一名热爱人工智能的学生，在校期间积极参与各类竞赛和项目，具有扎实的专业基础和实践能力。',
    resumeUrl: '/placeholder.pdf',
    status: 'seeking',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-06-20'),
  },
  {
    id: 'stu002',
    name: '王雨涵',
    gender: 'female',
    avatar: '/placeholder.svg?height=80&width=80',
    major: '软件技术',
    department: '信息工程学院',
    grade: '2021级',
    studentId: 'S2021015',
    phone: '13812345002',
    email: 'wangyuhan@student.hdvtc.edu.cn',
    expectedSalary: '12-18K',
    expectedLocation: '上海、苏州、杭州',
    skills: ['Java', 'Spring Boot', 'MySQL', 'Vue'],
    certificates: ['计算机等级证书', '软件工程师认证'],
    internshipExperience: '曾在上海云智科技实习4个月，参与企业级应用开发',
    selfIntroduction: '热爱编程，善于学习新技术。在团队项目中担任技术负责人，具有良好的沟通和协调能力。',
    resumeUrl: '/placeholder.pdf',
    status: 'seeking',
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-06-18'),
  },
  {
    id: 'stu003',
    name: '李明轩',
    gender: 'male',
    avatar: '/placeholder.svg?height=80&width=80',
    major: '新能源技术',
    department: '新能源学院',
    grade: '2021级',
    studentId: 'S2021028',
    phone: '13812345003',
    email: 'limingxuan@student.hdvtc.edu.cn',
    expectedSalary: '8-12K',
    expectedLocation: '南京、苏州',
    skills: ['光伏技术', '电力系统', '设备运维'],
    certificates: ['电工证', '光伏运维工程师'],
    internshipExperience: '在江苏新能源集团实训基地学习3个月',
    selfIntroduction: '对新能源行业充满热情，具有扎实的专业技能和动手能力。',
    resumeUrl: '/placeholder.pdf',
    status: 'seeking',
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2024-06-15'),
  },
]

// 岗位投递数据
export const jobApplications: JobApplication[] = [
  {
    id: 'app001',
    jobId: 'job001',
    jobTitle: 'AI算法工程师',
    partnerId: 'p001',
    partnerName: '苏州智联科技有限公司',
    studentId: 'stu001',
    studentName: '陈思远',
    studentMajor: '人工智能应用技术',
    studentPhone: '13812345001',
    studentEmail: 'chensiyuan@student.hdvtc.edu.cn',
    resumeUrl: '/placeholder.pdf',
    coverLetter: '尊敬的HR，我是华东职业技术学院人工智能应用技术专业的学生，对贵公司的AI算法工程师岗位非常感兴趣...',
    status: 'interview',
    interviewTime: new Date('2024-07-05 14:00'),
    interviewLocation: '苏州智联科技总部3楼会议室',
    appliedAt: new Date('2024-06-20'),
    updatedAt: new Date('2024-06-25'),
  },
  {
    id: 'app002',
    jobId: 'job002',
    jobTitle: 'Java开发工程师',
    partnerId: 'p001',
    partnerName: '苏州智联科技有限公司',
    studentId: 'stu002',
    studentName: '王雨涵',
    studentMajor: '软件技术',
    studentPhone: '13812345002',
    studentEmail: 'wangyuhan@student.hdvtc.edu.cn',
    resumeUrl: '/placeholder.pdf',
    coverLetter: '尊敬的HR，我对Java开发有浓厚的兴趣，希望能加入贵公司的开发团队...',
    status: 'offer',
    offerSalary: 14000,
    appliedAt: new Date('2024-06-15'),
    updatedAt: new Date('2024-06-28'),
  },
  {
    id: 'app003',
    jobId: 'job003',
    jobTitle: '新能源技术实习生',
    partnerId: 'p002',
    partnerName: '江苏新能源集团',
    studentId: 'stu003',
    studentName: '李明轩',
    studentMajor: '新能源技术',
    studentPhone: '13812345003',
    studentEmail: 'limingxuan@student.hdvtc.edu.cn',
    resumeUrl: '/placeholder.pdf',
    status: 'viewed',
    appliedAt: new Date('2024-06-22'),
    updatedAt: new Date('2024-06-23'),
  },
  {
    id: 'app004',
    jobId: 'job001',
    jobTitle: 'AI算法工程师',
    partnerId: 'p001',
    partnerName: '苏州智联科技有限公司',
    studentId: 'stu002',
    studentName: '王雨涵',
    studentMajor: '软件技术',
    studentPhone: '13812345002',
    studentEmail: 'wangyuhan@student.hdvtc.edu.cn',
    resumeUrl: '/placeholder.pdf',
    status: 'rejected',
    feedback: '专业背景与岗位要求不太匹配，建议投递软件开发类岗位',
    appliedAt: new Date('2024-06-18'),
    updatedAt: new Date('2024-06-22'),
  },
  {
    id: 'app005',
    jobId: 'job004',
    jobTitle: '前端开发工程师',
    partnerId: 'p001',
    partnerName: '苏州智联科技有限公司',
    studentId: 'stu002',
    studentName: '王雨涵',
    studentMajor: '软件技术',
    studentPhone: '13812345002',
    studentEmail: 'wangyuhan@student.hdvtc.edu.cn',
    resumeUrl: '/placeholder.pdf',
    status: 'pending',
    appliedAt: new Date('2024-06-25'),
    updatedAt: new Date('2024-06-25'),
  },
]

// 就业统计数据
export const employmentStats: EmploymentStats = {
  totalJobs: jobs.length,
  activeJobs: jobs.filter(j => j.status === 'published').length,
  totalApplications: jobApplications.length,
  pendingApplications: jobApplications.filter(a => a.status === 'pending').length,
  interviewCount: jobApplications.filter(a => a.status === 'interview').length,
  hiredCount: jobApplications.filter(a => a.status === 'hired').length,
  jobsByType: {
    'full-time': jobs.filter(j => j.type === 'full-time').length,
    'part-time': jobs.filter(j => j.type === 'part-time').length,
    internship: jobs.filter(j => j.type === 'internship').length,
    apprentice: jobs.filter(j => j.type === 'apprentice').length,
  },
  applicationsByStatus: {
    pending: jobApplications.filter(a => a.status === 'pending').length,
    viewed: jobApplications.filter(a => a.status === 'viewed').length,
    interview: jobApplications.filter(a => a.status === 'interview').length,
    offer: jobApplications.filter(a => a.status === 'offer').length,
    hired: jobApplications.filter(a => a.status === 'hired').length,
    rejected: jobApplications.filter(a => a.status === 'rejected').length,
    withdrawn: jobApplications.filter(a => a.status === 'withdrawn').length,
  },
  topPartners: [
    { partnerId: 'p001', partnerName: '苏州智联科技有限公司', jobCount: 4 },
    { partnerId: 'p002', partnerName: '江苏新能源集团', jobCount: 1 },
    { partnerId: 'p006', partnerName: '杭州智能制造有限公司', jobCount: 1 },
  ],
  topMajors: [
    { major: '软件技术', applicationCount: 3 },
    { major: '人工智能应用技术', applicationCount: 1 },
    { major: '新能源技术', applicationCount: 1 },
  ],
}

// 辅助函数：获取就业服务数据
export function getJobById(id: string): Job | undefined {
  return jobs.find(j => j.id === id)
}

export function getStudentProfileById(id: string): StudentProfile | undefined {
  return studentProfiles.find(s => s.id === id)
}

export function getJobApplicationById(id: string): JobApplication | undefined {
  return jobApplications.find(a => a.id === id)
}

export function getApplicationsByJobId(jobId: string): JobApplication[] {
  return jobApplications.filter(a => a.jobId === jobId)
}

export function getApplicationsByStudentId(studentId: string): JobApplication[] {
  return jobApplications.filter(a => a.studentId === studentId)
}
