import re

with open('lib/mock-data.ts', 'r', encoding='utf-8') as f:
    content = f.read()

# Partners 补充数据（7条）
partners_extra = """
  {
    id: 'p009',
    type: 'enterprise',
    name: '南京生物医药有限公司',
    industry: '生物医药',
    region: '江苏省南京市',
    description: '专注于创新药物研发和生物制品生产的国家高新技术企业，拥有多个在研新药项目。',
    logo: '/placeholder.svg?height=64&width=64',
    status: 'active',
    rating: 'deep',
    cooperationTypes: ['人才培养', '技术研发', '实习实训'],
    contactPerson: '吴敏',
    contactPhone: '13100131009',
    contactEmail: 'wumin@njbiomed.com',
    address: '南京市江宁区生物医药谷',
    establishedYear: 2014,
    employeeCount: 600,
    createdAt: new Date('2023-10-10'),
    updatedAt: new Date('2024-06-01'),
  },
  {
    id: 'p010',
    type: 'institution',
    name: '江苏省现代服务业研究院',
    industry: '金融服务',
    region: '江苏省南京市',
    description: '省级现代服务业研究智库，承担产业政策研究、行业标准制定、人才培训等工作。',
    logo: '/placeholder.svg?height=64&width=64',
    status: 'active',
    rating: 'general',
    cooperationTypes: ['课程共建', '师资培训', '产学研合作'],
    contactPerson: '郑华',
    contactPhone: '13000130010',
    contactEmail: 'zhenghua@jsmsri.org',
    address: '南京市鼓楼区中山路88号',
    establishedYear: 2010,
    employeeCount: 80,
    createdAt: new Date('2023-11-20'),
    updatedAt: new Date('2024-05-20'),
  },
  {
    id: 'p011',
    type: 'enterprise',
    name: '苏州文化创意集团',
    industry: '文化创意',
    region: '江苏省苏州市',
    description: '集文创设计、数字内容制作、文化IP运营于一体的综合性文化企业，与多所高校建立产学研合作。',
    logo: '/placeholder.svg?height=64&width=64',
    status: 'active',
    rating: 'general',
    cooperationTypes: ['人才培养', '实习实训', '创新创业'],
    contactPerson: '孙悦',
    contactPhone: '12900129011',
    contactEmail: 'sunyue@szccg.com',
    address: '苏州市姑苏区平江路文创园',
    establishedYear: 2016,
    employeeCount: 200,
    createdAt: new Date('2023-12-05'),
    updatedAt: new Date('2024-04-15'),
  },
  {
    id: 'p012',
    type: 'association',
    name: '江苏省电子商务协会',
    industry: '电子商务',
    region: '江苏省南京市',
    description: '由省内电商企业、平台、服务机构组成的行业组织，推动电商人才培养和产业数字化转型。',
    logo: '/placeholder.svg?height=64&width=64',
    status: 'active',
    rating: 'deep',
    cooperationTypes: ['人才培养', '技能竞赛', '课程共建'],
    contactPerson: '钱进',
    contactPhone: '12800128012',
    contactEmail: 'qianjin@jseca.org',
    address: '南京市建邺区河西CBD',
    establishedYear: 2015,
    employeeCount: 35,
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-06-10'),
  },
  {
    id: 'p013',
    type: 'park',
    name: '南京软件谷',
    industry: '信息技术',
    region: '江苏省南京市',
    description: '国家级软件产业基地，集聚软件企业3000余家，是江苏省软件产业的核心集聚区。',
    logo: '/placeholder.svg?height=64&width=64',
    status: 'active',
    rating: 'strategic',
    cooperationTypes: ['实习实训', '就业合作', '创新创业', '技术研发'],
    contactPerson: '李想',
    contactPhone: '12700127013',
    contactEmail: 'lixiang@njsoftwarevalley.com',
    address: '南京市雨花台区软件大道',
    establishedYear: 2011,
    employeeCount: 100,
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2024-05-25'),
  },
  {
    id: 'p014',
    type: 'enterprise',
    name: '无锡智能制造装备有限公司',
    industry: '智能制造',
    region: '江苏省无锡市',
    description: '专业从事智能装备研发和制造的国家专精特新企业，为汽车、电子等行业提供自动化解决方案。',
    logo: '/placeholder.svg?height=64&width=64',
    status: 'negotiating',
    rating: 'general',
    cooperationTypes: ['人才培养', '技术研发'],
    contactPerson: '周涛',
    contactPhone: '12600126014',
    contactEmail: 'zhoutao@wxim.com',
    address: '无锡市新吴区智能制造产业园',
    establishedYear: 2013,
    employeeCount: 450,
    createdAt: new Date('2024-03-20'),
    updatedAt: new Date('2024-06-05'),
  },
  {
    id: 'p015',
    type: 'expert',
    name: '陈明远',
    industry: '人工智能',
    region: '江苏省苏州市',
    description: '独立AI技术专家，曾任多家科技公司技术顾问，专注于自然语言处理和知识图谱领域。',
    logo: '/placeholder.svg?height=64&width=64',
    status: 'active',
    rating: 'deep',
    cooperationTypes: ['技术研发', '师资培训', '课程共建'],
    contactPerson: '陈明远',
    contactPhone: '12500125015',
    contactEmail: 'chenmy@ai-expert.com',
    address: '苏州市工业园区',
    establishedYear: 2010,
    employeeCount: 1,
    createdAt: new Date('2024-04-01'),
    updatedAt: new Date('2024-06-15'),
  },"""

# 在 partners 数组的最后一个元素后插入
pattern = r"(export const partners: Partner\[\] = \[.*?)(\n\])"
match = re.search(pattern, content, re.DOTALL)
if match:
    insert_pos = match.start(2)
    content = content[:insert_pos] + partners_extra + content[insert_pos:]

# Agreements 补充（6条）
agreements_extra = """
  {
    id: 'a007',
    name: '师资培训合作协议',
    partnerId: 'p005',
    partnerName: '中国职业教育发展研究院',
    type: '师资培训协议',
    content: '联合开展双师型教师培养，每年选派教师参加研究院组织的高级研修班。',
    startDate: new Date('2024-01-01'),
    endDate: new Date('2026-12-31'),
    status: 'active',
    attachments: ['协议正文.pdf'],
    createdAt: new Date('2023-12-10'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'a008',
    name: '创新创业合作协议',
    partnerId: 'p004',
    partnerName: '苏州工业园区人工智能产业园',
    type: '创新创业协议',
    content: '共建大学生创新创业孵化平台，提供场地、资金、导师等全方位支持。',
    startDate: new Date('2024-03-01'),
    endDate: new Date('2027-02-28'),
    status: 'active',
    attachments: ['合作协议.pdf', '实施细则.pdf'],
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2024-03-01'),
  },
  {
    id: 'a009',
    name: '技能竞赛合作协议',
    partnerId: 'p003',
    partnerName: '苏州市人工智能行业协会',
    type: '竞赛合作协议',
    content: '联合举办年度人工智能技能竞赛，共同制定竞赛标准和评审规则。',
    startDate: new Date('2024-01-01'),
    endDate: new Date('2025-12-31'),
    status: 'active',
    attachments: ['竞赛协议.pdf'],
    createdAt: new Date('2023-12-20'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'a010',
    name: '生物医药合作协议',
    partnerId: 'p009',
    partnerName: '南京生物医药有限公司',
    type: '产学研合作协议',
    content: '共建生物医药实训基地，开展药物检测技术培训和联合研发项目。',
    startDate: new Date('2024-04-01'),
    endDate: new Date('2027-03-31'),
    status: 'active',
    attachments: ['合作协议.pdf'],
    createdAt: new Date('2024-03-15'),
    updatedAt: new Date('2024-04-01'),
  },
  {
    id: 'a011',
    name: '电子商务合作协议',
    partnerId: 'p012',
    partnerName: '江苏省电子商务协会',
    type: '人才培养协议',
    content: '联合培养电商运营人才，共建电商直播实训室，开展行业认证培训。',
    startDate: new Date('2024-05-01'),
    endDate: new Date('2026-04-30'),
    status: 'active',
    attachments: ['协议正文.pdf'],
    createdAt: new Date('2024-04-10'),
    updatedAt: new Date('2024-05-01'),
  },
  {
    id: 'a012',
    name: '软件人才合作协议',
    partnerId: 'p013',
    partnerName: '南京软件谷',
    type: '就业合作协议',
    content: '建立软件人才定向培养通道，园区企业优先录用学院毕业生，每年提供实习岗位不少于200个。',
    startDate: new Date('2024-06-01'),
    endDate: new Date('2027-05-31'),
    status: 'active',
    attachments: ['合作协议.pdf', '企业名单.pdf'],
    createdAt: new Date('2024-05-15'),
    updatedAt: new Date('2024-06-01'),
  },"""

pattern = r"(export const agreements: Agreement\[\] = \[.*?)(\n\])"
match = re.search(pattern, content, re.DOTALL)
if match:
    insert_pos = match.start(2)
    content = content[:insert_pos] + agreements_extra + content[insert_pos:]

# Projects 补充（7条）
projects_extra = """
  {
    id: 'proj006',
    name: '生物医药检测技术实训基地建设',
    partnerId: 'p009',
    partnerName: '南京生物医药有限公司',
    type: '基地建设项目',
    agreementId: 'a010',
    phase: 'execution',
    description: '建设生物医药检测技术实训基地，配备HPLC、GC-MS等先进检测设备，培养药物检测技术人才。',
    startDate: new Date('2024-04-01'),
    endDate: new Date('2025-12-31'),
    budget: 400000,
    milestones: [
      { id: 'm1', name: '设备采购', description: '完成检测设备采购', dueDate: new Date('2024-08-31'), completedDate: new Date('2024-08-20'), status: 'completed' },
      { id: 'm2', name: '场地装修', description: '完成实验室装修', dueDate: new Date('2024-10-31'), status: 'in-progress' },
      { id: 'm3', name: '课程开发', description: '完成实训课程开发', dueDate: new Date('2025-03-31'), status: 'pending' },
      { id: 'm4', name: '试运营', description: '基地投入试运营', dueDate: new Date('2025-09-30'), status: 'pending' },
    ],
    outputs: ['实训基地1个', '实训课程5门', '检测项目库1个'],
    createdAt: new Date('2024-03-15'),
    updatedAt: new Date('2024-08-25'),
  },
  {
    id: 'proj007',
    name: '电商直播运营人才培养项目',
    partnerId: 'p012',
    partnerName: '江苏省电子商务协会',
    type: '人才培养项目',
    agreementId: 'a011',
    phase: 'initiation',
    description: '面向电子商务专业，培养具备直播运营、短视频制作、数据分析能力的复合型人才。',
    startDate: new Date('2024-09-01'),
    endDate: new Date('2026-06-30'),
    budget: 350000,
    milestones: [
      { id: 'm1', name: '需求调研', description: '完成电商行业人才需求调研', dueDate: new Date('2024-10-31'), status: 'pending' },
      { id: 'm2', name: '方案制定', description: '完成人才培养方案制定', dueDate: new Date('2024-12-31'), status: 'pending' },
      { id: 'm3', name: '课程开发', description: '完成核心课程开发', dueDate: new Date('2025-06-30'), status: 'pending' },
    ],
    outputs: ['人才培养方案1套', '直播课程3门', '实训项目库1个'],
    createdAt: new Date('2024-08-01'),
    updatedAt: new Date('2024-08-15'),
  },
  {
    id: 'proj008',
    name: '软件人才定向培养项目',
    partnerId: 'p013',
    partnerName: '南京软件谷',
    type: '人才培养项目',
    agreementId: 'a012',
    phase: 'execution',
    description: '与南京软件谷合作开展软件人才定向培养，采用"2+1"校企联合培养模式。',
    startDate: new Date('2024-06-01'),
    endDate: new Date('2025-05-31'),
    budget: 600000,
    milestones: [
      { id: 'm1', name: '企业调研', description: '完成园区企业人才需求调研', dueDate: new Date('2024-07-31'), completedDate: new Date('2024-07-25'), status: 'completed' },
      { id: 'm2', name: '课程定制', description: '完成定向培养课程定制', dueDate: new Date('2024-10-31'), status: 'in-progress' },
      { id: 'm3', name: '双师组建', description: '组建校企双师教学团队', dueDate: new Date('2024-12-31'), status: 'pending' },
      { id: 'm4', name: '试点实施', description: '开展定向培养试点', dueDate: new Date('2025-05-31'), status: 'pending' },
    ],
    outputs: ['定向培养方案1套', '企业课程模块5个', '双师团队1支'],
    createdAt: new Date('2024-05-15'),
    updatedAt: new Date('2024-07-30'),
  },
  {
    id: 'proj009',
    name: '文化创意产品设计项目',
    partnerId: 'p011',
    partnerName: '苏州文化创意集团',
    type: '技术研发项目',
    phase: 'initiation',
    description: '联合开发具有地方特色的文创产品，培养学生创新设计能力和市场运营能力。',
    startDate: new Date('2024-10-01'),
    endDate: new Date('2025-09-30'),
    budget: 150000,
    milestones: [
      { id: 'm1', name: '市场调研', description: '完成文创市场调研', dueDate: new Date('2024-11-30'), status: 'pending' },
      { id: 'm2', name: '产品设计', description: '完成文创产品设计', dueDate: new Date('2025-03-31'), status: 'pending' },
      { id: 'm3', name: '产品孵化', description: '完成产品打样和市场测试', dueDate: new Date('2025-07-31'), status: 'pending' },
    ],
    outputs: ['文创产品3款', '设计案例库1个'],
    createdAt: new Date('2024-09-01'),
    updatedAt: new Date('2024-09-10'),
  },
  {
    id: 'proj010',
    name: '现代服务业师资培训项目',
    partnerId: 'p010',
    partnerName: '江苏省现代服务业研究院',
    type: '师资培训项目',
    phase: 'execution',
    description: '面向现代服务类专业教师，开展产业前沿知识和教学方法培训。',
    startDate: new Date('2024-07-01'),
    endDate: new Date('2025-06-30'),
    budget: 200000,
    milestones: [
      { id: 'm1', name: '培训设计', description: '完成培训课程体系设计', dueDate: new Date('2024-08-31'), completedDate: new Date('2024-08-25'), status: 'completed' },
      { id: 'm2', name: '首期培训', description: '完成首期教师培训', dueDate: new Date('2024-12-31'), status: 'in-progress' },
      { id: 'm3', name: '成果总结', description: '完成培训成果总结', dueDate: new Date('2025-06-30'), status: 'pending' },
    ],
    outputs: ['培训课程体系1套', '培训师资库1个', '培训案例集1册'],
    createdAt: new Date('2024-06-15'),
    updatedAt: new Date('2024-08-30'),
  },
  {
    id: 'proj011',
    name: '智能制造装备技术攻关项目',
    partnerId: 'p014',
    partnerName: '无锡智能制造装备有限公司',
    type: '技术研发项目',
    phase: 'initiation',
    description: '联合开展工业机器人视觉引导系统技术攻关，解决精密装配中的定位难题。',
    startDate: new Date('2024-11-01'),
    endDate: new Date('2026-10-31'),
    budget: 900000,
    milestones: [
      { id: 'm1', name: '需求分析', description: '完成技术需求分析', dueDate: new Date('2024-12-31'), status: 'pending' },
      { id: 'm2', name: '方案设计', description: '完成系统方案设计', dueDate: new Date('2025-03-31'), status: 'pending' },
      { id: 'm3', name: '原型开发', description: '完成系统原型开发', dueDate: new Date('2025-09-30'), status: 'pending' },
      { id: 'm4', name: '现场测试', description: '完成现场应用测试', dueDate: new Date('2026-04-30'), status: 'pending' },
    ],
    outputs: ['技术方案1套', '软件系统1套', '专利申请2项'],
    createdAt: new Date('2024-10-01'),
    updatedAt: new Date('2024-10-05'),
  },
  {
    id: 'proj012',
    name: 'AI技术社区科普活动',
    partnerId: 'p015',
    partnerName: '陈明远',
    type: '社会服务项目',
    phase: 'execution',
    description: '面向社区居民和中小学生开展人工智能科普讲座和体验活动，提升公众AI素养。',
    startDate: new Date('2024-08-01'),
    endDate: new Date('2025-07-31'),
    budget: 80000,
    milestones: [
      { id: 'm1', name: '课程开发', description: '完成科普课程开发', dueDate: new Date('2024-09-30'), completedDate: new Date('2024-09-25'), status: 'completed' },
      { id: 'm2', name: '试点讲座', description: '完成3场试点讲座', dueDate: new Date('2024-12-31'), status: 'in-progress' },
      { id: 'm3', name: '全面推广', description: '覆盖10个社区开展讲座', dueDate: new Date('2025-06-30'), status: 'pending' },
    ],
    outputs: ['科普课程3门', '活动手册1册', '媒体报道5篇'],
    createdAt: new Date('2024-07-15'),
    updatedAt: new Date('2024-09-28'),
  },"""

pattern = r"(export const projects: Project\[\] = \[.*?)(\n\])"
match = re.search(pattern, content, re.DOTALL)
if match:
    insert_pos = match.start(2)
    content = content[:insert_pos] + projects_extra + content[insert_pos:]

# Experts 补充（6条）
experts_extra = """
  {
    id: 'e007',
    name: '吴敏',
    partnerId: 'p009',
    partnerName: '南京生物医药有限公司',
    title: '研发总监',
    field: '生物医药',
    specialties: ['药物化学', '制剂研发', '质量分析'],
    experience: 14,
    rating: 'gold',
    avatar: '/placeholder.svg?height=80&width=80',
    roles: ['产业导师', '技术顾问', '课程开发'],
    education: '中国药科大学博士',
    achievements: ['主持新药研发项目8项', '发表SCI论文30余篇', '获得发明专利12项'],
    contactEmail: 'wumin@njbiomed.com',
    contactPhone: '13100131009',
    status: 'active',
    createdAt: new Date('2023-10-15'),
    updatedAt: new Date('2024-06-10'),
  },
  {
    id: 'e008',
    name: '郑华',
    partnerId: 'p010',
    partnerName: '江苏省现代服务业研究院',
    title: '副院长',
    field: '金融服务',
    specialties: ['产业经济', '数字经济', '服务贸易'],
    experience: 16,
    rating: 'silver',
    avatar: '/placeholder.svg?height=80&width=80',
    roles: ['客座教授', '评审专家'],
    education: '南京大学经济学博士',
    achievements: ['主持省级课题6项', '出版专著2部', '参与制定行业标准3项'],
    contactEmail: 'zhenghua@jsmsri.org',
    contactPhone: '13000130010',
    status: 'active',
    createdAt: new Date('2023-11-25'),
    updatedAt: new Date('2024-05-20'),
  },
  {
    id: 'e009',
    name: '孙悦',
    partnerId: 'p011',
    partnerName: '苏州文化创意集团',
    title: '创意总监',
    field: '文化创意',
    specialties: ['品牌设计', 'IP运营', '数字内容'],
    experience: 11,
    rating: 'silver',
    avatar: '/placeholder.svg?height=80&width=80',
    roles: ['创业导师', '课程开发'],
    education: '中国美术学院硕士',
    achievements: ['设计作品获红点奖2项', '主导IP项目营收超千万', '出版设计教材1部'],
    contactEmail: 'sunyue@szccg.com',
    contactPhone: '12900129011',
    status: 'active',
    createdAt: new Date('2023-12-15'),
    updatedAt: new Date('2024-04-25'),
  },
  {
    id: 'e010',
    name: '钱进',
    partnerId: 'p012',
    partnerName: '江苏省电子商务协会',
    title: '培训部主任',
    field: '电子商务',
    specialties: ['电商运营', '直播营销', '数据分析'],
    experience: 9,
    rating: 'bronze',
    avatar: '/placeholder.svg?height=80&width=80',
    roles: ['产业导师', '竞赛评委'],
    education: '东南大学MBA',
    achievements: ['组织培训活动100余场', '培养电商人才5000余人', '主导行业标准制定1项'],
    contactEmail: 'qianjin@jseca.org',
    contactPhone: '12800128012',
    status: 'active',
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'e011',
    name: '李想',
    partnerId: 'p013',
    partnerName: '南京软件谷',
    title: '人才服务总监',
    field: '信息技术',
    specialties: ['人才发展', '企业培训', '校企合作'],
    experience: 13,
    rating: 'gold',
    avatar: '/placeholder.svg?height=80&width=80',
    roles: ['客座教授', '产业导师', '评审专家'],
    education: '南京理工大学硕士',
    achievements: ['建立园区人才服务体系', '组织招聘活动200余场', '促成校企合作50余项'],
    contactEmail: 'lixiang@njsoftwarevalley.com',
    contactPhone: '12700127013',
    status: 'active',
    createdAt: new Date('2024-02-25'),
    updatedAt: new Date('2024-05-30'),
  },
  {
    id: 'e012',
    name: '周涛',
    partnerId: 'p014',
    partnerName: '无锡智能制造装备有限公司',
    title: '技术总监',
    field: '智能制造',
    specialties: ['机器视觉', '自动化控制', '精密装配'],
    experience: 17,
    rating: 'silver',
    avatar: '/placeholder.svg?height=80&width=80',
    roles: ['技术顾问', '课程开发'],
    education: '哈尔滨工业大学博士',
    achievements: ['主导视觉引导系统研发', '获得国家科技进步奖1项', '授权发明专利20项'],
    contactEmail: 'zhoutao@wxim.com',
    contactPhone: '12600126014',
    status: 'active',
    createdAt: new Date('2024-03-25'),
    updatedAt: new Date('2024-06-08'),
  },"""

pattern = r"(export const experts: Expert\[\] = \[.*?)(\n\])"
match = re.search(pattern, content, re.DOTALL)
if match:
    insert_pos = match.start(2)
    content = content[:insert_pos] + experts_extra + content[insert_pos:]

# Activities 补充（7条）
activities_extra = """
  {
    id: 'act006',
    name: '2024年校企合作项目路演',
    type: '成果展示',
    date: new Date('2024-12-15'),
    location: '学校创新创业学院',
    description: '展示年度校企合作项目成果，邀请合作企业、行业专家、师生代表共同参与评审和交流。',
    status: 'draft',
    maxParticipants: 100,
    currentParticipants: 0,
    organizer: '产教融合办公室',
    coverImage: '/placeholder.svg?height=200&width=400',
    createdAt: new Date('2024-10-01'),
    updatedAt: new Date('2024-10-01'),
  },
  {
    id: 'act007',
    name: '生物医药行业专家讲座',
    type: '专题讲座',
    date: new Date('2024-11-20'),
    location: '医学工程学院报告厅',
    description: '邀请南京生物医药有限公司研发总监吴敏博士，分享生物医药行业发展趋势和人才需求。',
    status: 'published',
    maxParticipants: 120,
    currentParticipants: 85,
    organizer: '医学工程学院',
    coverImage: '/placeholder.svg?height=200&width=400',
    createdAt: new Date('2024-09-20'),
    updatedAt: new Date('2024-10-15'),
  },
  {
    id: 'act008',
    name: '电商直播技能大赛',
    type: '技能竞赛',
    date: new Date('2024-12-05'),
    endDate: new Date('2024-12-06'),
    location: '商学院实训中心',
    description: '联合江苏省电子商务协会举办，考核学生直播策划、产品讲解、互动营销等综合能力。',
    status: 'published',
    maxParticipants: 80,
    currentParticipants: 62,
    organizer: '商学院',
    coverImage: '/placeholder.svg?height=200&width=400',
    createdAt: new Date('2024-10-10'),
    updatedAt: new Date('2024-11-01'),
  },
  {
    id: 'act009',
    name: '南京软件谷企业开放日',
    type: '企业开放日',
    date: new Date('2024-11-15'),
    location: '南京软件谷园区',
    description: '组织学生赴南京软件谷参观交流，了解软件企业发展现状和人才需求，促进就业对接。',
    status: 'published',
    maxParticipants: 60,
    currentParticipants: 48,
    organizer: '就业指导中心',
    coverImage: '/placeholder.svg?height=200&width=400',
    createdAt: new Date('2024-09-25'),
    updatedAt: new Date('2024-10-20'),
  },
  {
    id: 'act010',
    name: '文创产品设计工作坊',
    type: '培训活动',
    date: new Date('2024-11-22'),
    location: '艺术设计学院工作室',
    description: '邀请苏州文化创意集团创意总监孙悦带领学生进行文创产品设计实战演练。',
    status: 'published',
    maxParticipants: 30,
    currentParticipants: 28,
    organizer: '艺术设计学院',
    coverImage: '/placeholder.svg?height=200&width=400',
    createdAt: new Date('2024-10-05'),
    updatedAt: new Date('2024-10-25'),
  },
  {
    id: 'act011',
    name: '智能制造技术研讨会',
    type: '研讨会',
    date: new Date('2024-12-10'),
    location: '机械工程学院会议室',
    description: '围绕工业机器视觉、智能装配等前沿技术，邀请企业专家和学术代表开展技术研讨。',
    status: 'draft',
    maxParticipants: 50,
    currentParticipants: 0,
    organizer: '机械工程学院',
    coverImage: '/placeholder.svg?height=200&width=400',
    createdAt: new Date('2024-10-15'),
    updatedAt: new Date('2024-10-15'),
  },
  {
    id: 'act012',
    name: '2025届毕业生双选会',
    type: '招聘会',
    date: new Date('2025-03-15'),
    location: '学校体育馆',
    description: '春季大型校园双选会，预计邀请80余家合作企业，提供就业岗位1500余个。',
    status: 'draft',
    maxParticipants: 800,
    currentParticipants: 0,
    organizer: '就业指导中心',
    coverImage: '/placeholder.svg?height=200&width=400',
    createdAt: new Date('2024-11-01'),
    updatedAt: new Date('2024-11-01'),
  },"""

pattern = r"(export const activities: Activity\[\] = \[.*?)(\n\])"
match = re.search(pattern, content, re.DOTALL)
if match:
    insert_pos = match.start(2)
    content = content[:insert_pos] + activities_extra + content[insert_pos:]

# Achievements 补充（9条）
achievements_extra = """
  {
    id: 'ach007',
    name: '电商直播运营实训室',
    type: 'training-base',
    partnerId: 'p012',
    partnerName: '江苏省电子商务协会',
    description: '共建电商直播运营实训室，配备专业直播间、短视频制作设备和数据分析平台。',
    images: ['/placeholder.svg?height=300&width=400'],
    publishDate: new Date('2024-07-15'),
    status: 'published',
    viewCount: 980,
    createdAt: new Date('2024-07-10'),
    updatedAt: new Date('2024-08-01'),
  },
  {
    id: 'ach008',
    name: '软件人才定向培养模式创新',
    type: 'case-study',
    partnerId: 'p013',
    partnerName: '南京软件谷',
    description: '探索"2+1"校企联合培养模式，学生前两年在校学习，第三年进入企业顶岗实习和项目实战。',
    images: ['/placeholder.svg?height=300&width=400'],
    publishDate: new Date('2024-08-20'),
    status: 'published',
    viewCount: 1320,
    createdAt: new Date('2024-08-15'),
    updatedAt: new Date('2024-09-01'),
  },
  {
    id: 'ach009',
    name: '生物医药检测技术课程群',
    type: 'education-reform',
    partnerId: 'p009',
    partnerName: '南京生物医药有限公司',
    description: '联合开发生物医药检测技术课程群，涵盖药物分析、质量检测、仪器操作等核心内容。',
    images: ['/placeholder.svg?height=300&width=400'],
    publishDate: new Date('2024-09-10'),
    status: 'published',
    viewCount: 760,
    createdAt: new Date('2024-09-05'),
    updatedAt: new Date('2024-09-20'),
  },
  {
    id: 'ach010',
    name: '文创产品设计方案集',
    type: 'patent',
    partnerId: 'p011',
    partnerName: '苏州文化创意集团',
    description: '校企联合设计的苏州特色文创产品系列，已获得外观设计专利授权。',
    images: ['/placeholder.svg?height=300&width=400'],
    publishDate: new Date('2024-10-05'),
    status: 'published',
    viewCount: 890,
    createdAt: new Date('2024-10-01'),
    updatedAt: new Date('2024-10-15'),
  },
  {
    id: 'ach011',
    name: '现代服务业师资培训基地',
    type: 'award',
    partnerId: 'p010',
    partnerName: '江苏省现代服务业研究院',
    description: '与现代服务业研究院共建的师资培训基地被评为省级双师型教师培养培训基地。',
    images: ['/placeholder.svg?height=300&width=400'],
    publishDate: new Date('2024-10-25'),
    status: 'published',
    viewCount: 650,
    createdAt: new Date('2024-10-20'),
    updatedAt: new Date('2024-11-01'),
  },
  {
    id: 'ach012',
    name: '智能制造视觉引导系统',
    type: 'patent',
    partnerId: 'p014',
    partnerName: '无锡智能制造装备有限公司',
    description: '校企联合研发的工业机器人视觉引导系统，获得国家发明专利授权。',
    images: ['/placeholder.svg?height=300&width=400'],
    publishDate: new Date('2024-11-10'),
    status: 'draft',
    viewCount: 420,
    createdAt: new Date('2024-11-05'),
    updatedAt: new Date('2024-11-10'),
  },
  {
    id: 'ach013',
    name: 'AI科普进社区系列活动',
    type: 'case-study',
    partnerId: 'p015',
    partnerName: '陈明远',
    description: '面向社区居民和中小学生开展人工智能科普活动，覆盖10个社区，受益人群超3000人。',
    images: ['/placeholder.svg?height=300&width=400'],
    publishDate: new Date('2024-11-20'),
    status: 'published',
    viewCount: 1100,
    createdAt: new Date('2024-11-15'),
    updatedAt: new Date('2024-11-25'),
  },
  {
    id: 'ach014',
    name: '跨境电商运营实战项目',
    type: 'joint-build',
    partnerId: 'p012',
    partnerName: '江苏省电子商务协会',
    description: '共建跨境电商运营实战项目，学生在校期间即可参与真实店铺运营，积累实战经验。',
    images: ['/placeholder.svg?height=300&width=400'],
    publishDate: new Date('2024-12-01'),
    status: 'draft',
    viewCount: 340,
    createdAt: new Date('2024-11-25'),
    updatedAt: new Date('2024-12-01'),
  },
  {
    id: 'ach015',
    name: '文化创意产业学院',
    type: 'joint-build',
    partnerId: 'p011',
    partnerName: '苏州文化创意集团',
    description: '校企共建文化创意产业学院，整合设计、营销、技术等资源，培养文创产业复合型人才。',
    images: ['/placeholder.svg?height=300&width=400'],
    publishDate: new Date('2024-12-10'),
    status: 'draft',
    viewCount: 280,
    createdAt: new Date('2024-12-05'),
    updatedAt: new Date('2024-12-10'),
  },"""

pattern = r"(export const achievements: Achievement\[\] = \[.*?)(\n\])"
match = re.search(pattern, content, re.DOTALL)
if match:
    insert_pos = match.start(2)
    content = content[:insert_pos] + achievements_extra + content[insert_pos:]

with open('lib/mock-data.ts', 'w', encoding='utf-8') as f:
    f.write(content)

print("Batch 1 done: partners +7, agreements +6, projects +7, experts +6, activities +7, achievements +9")
