import re

with open('lib/mock-data.ts', 'r', encoding='utf-8') as f:
    content = f.read()

# talentProfiles 补充（10条）
talent_extra = """
  {
    id: 'tp006',
    studentId: 'S2022025',
    studentName: '周晓峰',
    major: '新能源技术',
    department: '新能源学院',
    grade: '2022级',
    avatar: '/placeholder.svg?height=80&width=80',
    abilityScore: 88.5,
    certificationLevel: '中级',
    taskCompletionRate: 90,
    comprehensiveRank: 6,
    abilityTags: ['光伏技术', '电力电子', '储能系统'],
    employmentStatus: 'seeking',
    isFeatured: false,
    updatedAt: new Date('2024-05-28'),
  },
  {
    id: 'tp007',
    studentId: 'S2021032',
    studentName: '赵静雯',
    major: '软件技术',
    department: '信息工程学院',
    grade: '2021级',
    avatar: '/placeholder.svg?height=80&width=80',
    abilityScore: 92.1,
    certificationLevel: '高级',
    taskCompletionRate: 95,
    comprehensiveRank: 7,
    abilityTags: ['前端开发', 'React', 'UI设计', 'TypeScript'],
    employmentStatus: 'employed',
    employmentCompany: '苏州智联科技有限公司',
    employmentPosition: '前端开发工程师',
    isFeatured: true,
    updatedAt: new Date('2024-06-18'),
  },
  {
    id: 'tp008',
    studentId: 'S2021045',
    studentName: '孙浩然',
    major: '智能制造技术',
    department: '机械工程学院',
    grade: '2021级',
    avatar: '/placeholder.svg?height=80&width=80',
    abilityScore: 87.3,
    certificationLevel: '中级',
    taskCompletionRate: 89,
    comprehensiveRank: 8,
    abilityTags: ['CAD设计', '数控加工', 'PLC编程'],
    employmentStatus: 'employed',
    employmentCompany: '杭州智能制造有限公司',
    employmentPosition: '数控编程员',
    isFeatured: false,
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'tp009',
    studentId: 'S2022038',
    studentName: '林小雅',
    major: '大数据技术',
    department: '信息工程学院',
    grade: '2022级',
    avatar: '/placeholder.svg?height=80&width=80',
    abilityScore: 86.8,
    certificationLevel: '中级',
    taskCompletionRate: 88,
    comprehensiveRank: 9,
    abilityTags: ['SQL', 'Python', '数据可视化', 'Hadoop'],
    employmentStatus: 'studying',
    isFeatured: false,
    updatedAt: new Date('2024-05-20'),
  },
  {
    id: 'tp010',
    studentId: 'S2021050',
    studentName: '吴志远',
    major: '人工智能应用技术',
    department: '信息工程学院',
    grade: '2021级',
    avatar: '/placeholder.svg?height=80&width=80',
    abilityScore: 94.2,
    certificationLevel: '高级',
    taskCompletionRate: 97,
    comprehensiveRank: 10,
    abilityTags: ['NLP', '知识图谱', 'PyTorch', '算法优化'],
    employmentStatus: 'employed',
    employmentCompany: '上海云智科技股份有限公司',
    employmentPosition: 'AI算法工程师',
    isFeatured: true,
    updatedAt: new Date('2024-06-22'),
  },
  {
    id: 'tp011',
    studentId: 'S2022042',
    studentName: '郑欣怡',
    major: '电子商务',
    department: '商学院',
    grade: '2022级',
    avatar: '/placeholder.svg?height=80&width=80',
    abilityScore: 85.5,
    certificationLevel: '中级',
    taskCompletionRate: 87,
    comprehensiveRank: 11,
    abilityTags: ['电商运营', '直播带货', '数据分析', '营销策划'],
    employmentStatus: 'seeking',
    isFeatured: false,
    updatedAt: new Date('2024-05-15'),
  },
  {
    id: 'tp012',
    studentId: 'S2021060',
    studentName: '王鹏飞',
    major: '新能源技术',
    department: '新能源学院',
    grade: '2021级',
    avatar: '/placeholder.svg?height=80&width=80',
    abilityScore: 89.8,
    certificationLevel: '高级',
    taskCompletionRate: 93,
    comprehensiveRank: 12,
    abilityTags: ['风电技术', '电网调度', '新能源系统'],
    employmentStatus: 'employed',
    employmentCompany: '江苏新能源集团',
    employmentPosition: '风电运维工程师',
    isFeatured: false,
    updatedAt: new Date('2024-06-08'),
  },
  {
    id: 'tp013',
    studentId: 'S2022055',
    studentName: '黄嘉琪',
    major: '软件技术',
    department: '信息工程学院',
    grade: '2022级',
    avatar: '/placeholder.svg?height=80&width=80',
    abilityScore: 84.2,
    certificationLevel: '中级',
    taskCompletionRate: 86,
    comprehensiveRank: 13,
    abilityTags: ['Java', 'Spring Boot', 'MySQL', 'Redis'],
    employmentStatus: 'studying',
    isFeatured: false,
    updatedAt: new Date('2024-05-10'),
  },
  {
    id: 'tp014',
    studentId: 'S2021070',
    studentName: '刘思远',
    major: '智能制造技术',
    department: '机械工程学院',
    grade: '2021级',
    avatar: '/placeholder.svg?height=80&width=80',
    abilityScore: 91.5,
    certificationLevel: '高级',
    taskCompletionRate: 94,
    comprehensiveRank: 14,
    abilityTags: ['工业机器人', '机器视觉', '自动化集成'],
    employmentStatus: 'employed',
    employmentCompany: '无锡智能制造装备有限公司',
    employmentPosition: '自动化工程师',
    isFeatured: true,
    updatedAt: new Date('2024-06-25'),
  },
  {
    id: 'tp015',
    studentId: 'S2022065',
    studentName: '陈雨萱',
    major: '大数据技术',
    department: '信息工程学院',
    grade: '2022级',
    avatar: '/placeholder.svg?height=80&width=80',
    abilityScore: 83.8,
    certificationLevel: '初级',
    taskCompletionRate: 85,
    comprehensiveRank: 15,
    abilityTags: ['Excel', 'Python', '数据清洗', 'BI工具'],
    employmentStatus: 'seeking',
    isFeatured: false,
    updatedAt: new Date('2024-05-05'),
  },"""

pattern = r"(export const talentProfiles: TalentProfile\[\] = \[.*?)(\n\])"
match = re.search(pattern, content, re.DOTALL)
if match:
    insert_pos = match.start(2)
    content = content[:insert_pos] + talent_extra + content[insert_pos:]

# employmentCases 补充（7条）
cases_extra = """
  {
    id: 'ec004',
    studentName: '赵静雯',
    major: '软件技术',
    graduationYear: 2024,
    company: '苏州智联科技有限公司',
    companyLogo: '/placeholder.svg?height=64&width=64',
    position: '前端开发工程师',
    salary: '12-18K',
    abilityTags: ['React', 'TypeScript', 'UI设计'],
    story: '在校期间积极参与前端技术社区，多次在开源项目贡献代码。凭借扎实的技术功底和出色的设计能力，成功加入苏州智联科技前端团队。',
    photo: '/placeholder.svg?height=200&width=200',
    status: 'published',
    viewCount: 980,
    createdAt: new Date('2024-05-01'),
    updatedAt: new Date('2024-06-15'),
  },
  {
    id: 'ec005',
    studentName: '吴志远',
    major: '人工智能应用技术',
    graduationYear: 2024,
    company: '上海云智科技股份有限公司',
    companyLogo: '/placeholder.svg?height=64&width=64',
    position: 'AI算法工程师',
    salary: '18-25K',
    abilityTags: ['NLP', '知识图谱', '算法优化'],
    story: '在自然语言处理方向深入研究，发表学术论文2篇。毕业后加入上海云智科技，参与企业知识图谱平台的研发工作。',
    photo: '/placeholder.svg?height=200&width=200',
    status: 'published',
    viewCount: 1120,
    createdAt: new Date('2024-05-10'),
    updatedAt: new Date('2024-06-18'),
  },
  {
    id: 'ec006',
    studentName: '孙浩然',
    major: '智能制造技术',
    graduationYear: 2024,
    company: '杭州智能制造有限公司',
    companyLogo: '/placeholder.svg?height=64&width=64',
    position: '数控编程员',
    salary: '9-13K',
    abilityTags: ['CAD设计', '数控加工', 'PLC编程'],
    story: '在校期间多次获得数控技能竞赛奖项，毕业后进入杭州智能制造有限公司，从事数控编程和设备调试工作，快速成长为主力技术人员。',
    photo: '/placeholder.svg?height=200&width=200',
    status: 'published',
    viewCount: 850,
    createdAt: new Date('2024-05-15'),
    updatedAt: new Date('2024-06-10'),
  },
  {
    id: 'ec007',
    studentName: '王鹏飞',
    major: '新能源技术',
    graduationYear: 2024,
    company: '江苏新能源集团',
    companyLogo: '/placeholder.svg?height=64&width=64',
    position: '风电运维工程师',
    salary: '10-15K',
    abilityTags: ['风电技术', '电网调度', '设备维护'],
    story: '对新能源行业充满热情，在校期间系统学习了风电技术相关知识。毕业后入职江苏新能源集团，从事风电场的运维和技术管理工作。',
    photo: '/placeholder.svg?height=200&width=200',
    status: 'published',
    viewCount: 760,
    createdAt: new Date('2024-05-20'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'ec008',
    studentName: '刘思远',
    major: '智能制造技术',
    graduationYear: 2024,
    company: '无锡智能制造装备有限公司',
    companyLogo: '/placeholder.svg?height=64&width=64',
    position: '自动化工程师',
    salary: '11-16K',
    abilityTags: ['工业机器人', '机器视觉', '自动化集成'],
    story: '在校期间参与多个校企合作项目，积累了丰富的自动化系统集成经验。毕业后加入无锡智能制造装备有限公司，负责自动化产线的设计与实施。',
    photo: '/placeholder.svg?height=200&width=200',
    status: 'published',
    viewCount: 920,
    createdAt: new Date('2024-05-25'),
    updatedAt: new Date('2024-06-20'),
  },
  {
    id: 'ec009',
    studentName: '郑欣怡',
    major: '电子商务',
    graduationYear: 2024,
    company: '江苏省电子商务协会成员单位',
    companyLogo: '/placeholder.svg?height=64&width=64',
    position: '电商运营主管',
    salary: '8-12K',
    abilityTags: ['电商运营', '直播带货', '数据分析'],
    story: '在校期间运营个人电商账号取得优异成绩，毕业后加入电商企业，负责店铺运营和直播团队管理，半年内将店铺销售额提升300%。',
    photo: '/placeholder.svg?height=200&width=200',
    status: 'published',
    viewCount: 680,
    createdAt: new Date('2024-06-01'),
    updatedAt: new Date('2024-06-22'),
  },
  {
    id: 'ec010',
    studentName: '林小雅',
    major: '大数据技术',
    graduationYear: 2024,
    company: '苏州智联科技有限公司',
    companyLogo: '/placeholder.svg?height=64&width=64',
    position: '数据分析师',
    salary: '10-15K',
    abilityTags: ['SQL', 'Python', '数据可视化', '机器学习'],
    story: '对数据分析有浓厚兴趣，在校期间参与企业数据分析项目。毕业后加入苏州智联科技数据团队，负责业务数据分析和用户行为洞察。',
    photo: '/placeholder.svg?height=200&width=200',
    status: 'draft',
    viewCount: 450,
    createdAt: new Date('2024-06-05'),
    updatedAt: new Date('2024-06-25'),
  },"""

pattern = r"(export const employmentCases: EmploymentCase\[\] = \[.*?)(\n\])"
match = re.search(pattern, content, re.DOTALL)
if match:
    insert_pos = match.start(2)
    content = content[:insert_pos] + cases_extra + content[insert_pos:]

# jobBrands 补充（6条）
jobbrands_extra = """
  {
    id: 'jb005',
    name: '新能源运维工程师',
    industry: '新能源',
    level: 'key',
    description: '负责光伏电站和风电场的日常运维、故障处理和性能优化，保障发电系统的稳定运行。',
    abilityModel: ['电力系统', '设备运维', '故障诊断', '安全规范', '数据监控'],
    suitableMajors: ['新能源技术', '电气自动化', '电力系统'],
    averageSalary: '8-15K',
    demandCount: 86,
    featureTags: ['绿色产业', '政策支持', '就业前景好'],
    coverImage: '/placeholder.svg?height=200&width=300',
    status: 'published',
    viewCount: 1680,
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-06-15'),
  },
  {
    id: 'jb006',
    name: '电商运营专员',
    industry: '电子商务',
    level: 'standard',
    description: '负责电商平台店铺运营、商品管理、活动策划和数据分析，提升店铺销售业绩。',
    abilityModel: ['电商平台操作', '数据分析', '营销策划', '客户服务', '供应链管理'],
    suitableMajors: ['电子商务', '市场营销', '工商管理'],
    averageSalary: '6-12K',
    demandCount: 312,
    featureTags: ['需求量大', '晋升空间大', '创业友好'],
    coverImage: '/placeholder.svg?height=200&width=300',
    status: 'published',
    viewCount: 2450,
    createdAt: new Date('2024-03-10'),
    updatedAt: new Date('2024-06-10'),
  },
  {
    id: 'jb007',
    name: '生物医药研究员',
    industry: '生物医药',
    level: 'recommended',
    description: '参与新药研发项目，开展药物筛选、药理评价和质量研究工作。',
    abilityModel: ['药物化学', '药理学', '分析化学', '实验操作', '文献检索'],
    suitableMajors: ['药学', '生物技术', '化学工程'],
    averageSalary: '12-20K',
    demandCount: 45,
    featureTags: ['技术前沿', '社会价值高', '发展稳定'],
    coverImage: '/placeholder.svg?height=200&width=300',
    status: 'published',
    viewCount: 980,
    createdAt: new Date('2024-03-20'),
    updatedAt: new Date('2024-06-05'),
  },
  {
    id: 'jb008',
    name: '数据分析师',
    industry: '信息技术',
    level: 'key',
    description: '负责业务数据的收集、整理和分析，为运营决策提供数据支持和洞察。',
    abilityModel: ['SQL', 'Python', '数据可视化', '统计分析', '业务理解'],
    suitableMajors: ['大数据技术', '统计学', '软件技术'],
    averageSalary: '10-18K',
    demandCount: 198,
    featureTags: ['热门岗位', '跨行业适用', '薪资增长快'],
    coverImage: '/placeholder.svg?height=200&width=300',
    status: 'published',
    viewCount: 2100,
    createdAt: new Date('2024-04-01'),
    updatedAt: new Date('2024-06-20'),
  },
  {
    id: 'jb009',
    name: '文创产品设计师',
    industry: '文化创意',
    level: 'standard',
    description: '负责文创产品的创意设计、IP开发和视觉呈现，将文化元素转化为市场产品。',
    abilityModel: ['平面设计', 'IP开发', '品牌策划', '手绘能力', '市场洞察'],
    suitableMajors: ['视觉传达', '产品设计', '动画设计'],
    averageSalary: '7-14K',
    demandCount: 68,
    featureTags: ['创意工作', '文化底蕴', '市场潜力'],
    coverImage: '/placeholder.svg?height=200&width=300',
    status: 'published',
    viewCount: 1120,
    createdAt: new Date('2024-04-10'),
    updatedAt: new Date('2024-06-15'),
  },
  {
    id: 'jb010',
    name: '云计算运维工程师',
    industry: '信息技术',
    level: 'recommended',
    description: '负责云平台的日常运维、监控告警、故障处理和性能优化，保障云服务稳定运行。',
    abilityModel: ['Linux系统', '容器技术', '网络基础', '自动化运维', '故障排查'],
    suitableMajors: ['云计算技术', '网络工程', '软件技术'],
    averageSalary: '12-22K',
    demandCount: 175,
    featureTags: ['技术前沿', '薪资优厚', '发展空间大'],
    coverImage: '/placeholder.svg?height=200&width=300',
    status: 'published',
    viewCount: 1890,
    createdAt: new Date('2024-04-20'),
    updatedAt: new Date('2024-06-18'),
  },"""

pattern = r"(export const jobBrands: JobBrand\[\] = \[.*?)(\n\])"
match = re.search(pattern, content, re.DOTALL)
if match:
    insert_pos = match.start(2)
    content = content[:insert_pos] + jobbrands_extra + content[insert_pos:]

# majorBrands 补充（6条）
majorbrands_extra = """
  {
    id: 'mb005',
    name: '大数据技术',
    department: '信息工程学院',
    level: 'key',
    introduction: '本专业面向大数据产业，培养具备数据采集、存储、处理、分析和可视化能力的技术技能人才。',
    cultivationGoal: '培养掌握大数据技术体系，能够从事数据分析、数据开发和数据治理工作的技术技能人才。',
    coreCourses: ['Python程序设计', '大数据技术基础', 'Hadoop生态', '数据可视化', '机器学习基础'],
    employmentDirections: ['数据分析师', '大数据开发工程师', '数据仓库工程师', 'BI工程师'],
    cooperationPartners: ['苏州智联科技有限公司', '南京软件谷'],
    featuredAchievements: ['校级重点专业', '大数据实训基地'],
    studentCount: 260,
    employmentRate: 96.5,
    coverImage: '/placeholder.svg?height=300&width=500',
    status: 'published',
    viewCount: 2100,
    createdAt: new Date('2023-09-01'),
    updatedAt: new Date('2024-06-15'),
  },
  {
    id: 'mb006',
    name: '电子商务',
    department: '商学院',
    level: 'standard',
    introduction: '本专业面向电子商务行业，培养具备网店运营、直播营销、客户服务等能力的复合型人才。',
    cultivationGoal: '培养掌握电子商务运营全流程，能够从事网店运营、直播带货、跨境电商等工作的技术技能人才。',
    coreCourses: ['电子商务概论', '网店运营', '直播营销', '跨境电商', '数据分析'],
    employmentDirections: ['电商运营', '直播主播', '跨境电商专员', '客服主管'],
    cooperationPartners: ['江苏省电子商务协会'],
    featuredAchievements: ['电商直播实训室', '校企共建课程'],
    studentCount: 380,
    employmentRate: 95.8,
    coverImage: '/placeholder.svg?height=300&width=500',
    status: 'published',
    viewCount: 1780,
    createdAt: new Date('2023-09-01'),
    updatedAt: new Date('2024-06-10'),
  },
  {
    id: 'mb007',
    name: '电气自动化技术',
    department: '新能源学院',
    level: 'standard',
    introduction: '本专业面向电气自动化领域，培养具备电气系统设计、安装调试、运行维护能力的技术人才。',
    cultivationGoal: '培养掌握电气自动化技术，能够从事电气系统设计、PLC编程、自动化设备调试等工作的技术技能人才。',
    coreCourses: ['电路基础', '电机与拖动', 'PLC编程', '变频器技术', '自动控制系统'],
    employmentDirections: ['电气工程师', '自动化技术员', '设备维护工程师', '系统集成工程师'],
    cooperationPartners: ['江苏新能源集团', '杭州智能制造有限公司'],
    featuredAchievements: ['省级实训基地', '技能竞赛获奖'],
    studentCount: 220,
    employmentRate: 96.2,
    coverImage: '/placeholder.svg?height=300&width=500',
    status: 'published',
    viewCount: 1560,
    createdAt: new Date('2023-09-01'),
    updatedAt: new Date('2024-06-05'),
  },
  {
    id: 'mb008',
    name: '计算机网络技术',
    department: '信息工程学院',
    level: 'key',
    introduction: '本专业面向网络技术领域，培养具备网络规划、建设、运维和安全管理能力的技术人才。',
    cultivationGoal: '培养掌握计算机网络技术，能够从事网络工程、网络安全、云计算运维等工作的技术技能人才。',
    coreCourses: ['网络基础', '路由交换技术', '网络安全', 'Linux系统', '云计算技术'],
    employmentDirections: ['网络工程师', '网络安全工程师', '云计算运维', '系统管理员'],
    cooperationPartners: ['上海云智科技股份有限公司', '南京软件谷'],
    featuredAchievements: ['网络攻防实训室', '华为ICT学院'],
    studentCount: 300,
    employmentRate: 97.5,
    coverImage: '/placeholder.svg?height=300&width=500',
    status: 'published',
    viewCount: 1980,
    createdAt: new Date('2023-09-01'),
    updatedAt: new Date('2024-06-18'),
  },
  {
    id: 'mb009',
    name: '机电一体化技术',
    department: '机械工程学院',
    level: 'standard',
    introduction: '本专业面向机电一体化领域，培养具备机械设计、电气控制、自动化系统集成能力的复合型人才。',
    cultivationGoal: '培养掌握机电一体化技术，能够从事机电设备设计、安装调试、维护维修等工作的技术技能人才。',
    coreCourses: ['机械制图', '电工电子技术', 'PLC编程', '液压气动', '机电设备维修'],
    employmentDirections: ['机电工程师', '设备维护工程师', '自动化技术员', '质量检测员'],
    cooperationPartners: ['杭州智能制造有限公司', '无锡智能制造装备有限公司'],
    featuredAchievements: ['校企共建实训室', '技能竞赛二等奖'],
    studentCount: 180,
    employmentRate: 95.0,
    coverImage: '/placeholder.svg?height=300&width=500',
    status: 'published',
    viewCount: 1320,
    createdAt: new Date('2023-09-01'),
    updatedAt: new Date('2024-06-08'),
  },
  {
    id: 'mb010',
    name: '移动应用开发',
    department: '信息工程学院',
    level: 'key',
    introduction: '本专业面向移动互联网行业，培养具备Android和iOS应用开发能力的移动开发人才。',
    cultivationGoal: '培养掌握移动应用开发技术，能够从事App开发、小程序开发、移动游戏开发等工作的技术技能人才。',
    coreCourses: ['Java程序设计', 'Android开发', 'iOS开发', 'Flutter跨平台', '移动UI设计'],
    employmentDirections: ['移动开发工程师', 'Flutter工程师', '小程序开发', '游戏开发'],
    cooperationPartners: ['苏州智联科技有限公司'],
    featuredAchievements: ['移动开发工作室', 'App Store上架作品'],
    studentCount: 240,
    employmentRate: 96.8,
    coverImage: '/placeholder.svg?height=300&width=500',
    status: 'published',
    viewCount: 1670,
    createdAt: new Date('2023-09-01'),
    updatedAt: new Date('2024-06-12'),
  },"""

pattern = r"(export const majorBrands: MajorBrand\[\] = \[.*?)(\n\])"
match = re.search(pattern, content, re.DOTALL)
if match:
    insert_pos = match.start(2)
    content = content[:insert_pos] + majorbrands_extra + content[insert_pos:]

# teacherBrands 补充（6条）
teacherbrands_extra = """
  {
    id: 'tb005',
    name: '陈教授',
    department: '新能源学院',
    title: '教授',
    type: 'teaching-master',
    avatar: '/placeholder.svg?height=120&width=120',
    introduction: '省级教学名师，新能源技术专业带头人，长期从事光伏技术和储能技术教学与科研工作。',
    researchFields: ['光伏技术', '储能技术', '新能源系统'],
    achievements: ['主持国家级课题2项', '发表SCI论文20篇', '获省级教学成果一等奖'],
    courses: ['光伏发电技术', '储能技术', '新能源系统设计'],
    awards: ['省级教学名师', '省科技进步三等奖', '校优秀教师'],
    isFeatured: true,
    status: 'published',
    viewCount: 1980,
    createdAt: new Date('2023-08-01'),
    updatedAt: new Date('2024-06-18'),
  },
  {
    id: 'tb006',
    name: '赵讲师',
    department: '商学院',
    title: '讲师',
    type: 'dual-qualified',
    avatar: '/placeholder.svg?height=120&width=120',
    introduction: '双师型教师，曾在知名电商企业担任运营总监，具有丰富的电商实战经验和教学能力。',
    researchFields: ['电子商务', '直播营销', '数据分析'],
    achievements: ['运营企业店铺年销千万', '出版电商教材1部', '指导学生创业成功率80%'],
    courses: ['电子商务概论', '网店运营', '直播营销'],
    awards: ['双师型教师', '校教学能手', '优秀创业导师'],
    isFeatured: true,
    status: 'published',
    viewCount: 1560,
    createdAt: new Date('2023-08-15'),
    updatedAt: new Date('2024-06-15'),
  },
  {
    id: 'tb007',
    name: '钱副教授',
    department: '信息工程学院',
    title: '副教授',
    type: 'backbone',
    avatar: '/placeholder.svg?height=120&width=120',
    introduction: '骨干教师，大数据技术专业负责人，专注于数据分析和机器学习方向的教学与研究。',
    researchFields: ['大数据分析', '机器学习', '数据挖掘'],
    achievements: ['主持省部级课题3项', '发表核心期刊论文10篇', '开发数据分析课程5门'],
    courses: ['Python程序设计', '大数据技术基础', '机器学习基础'],
    awards: ['校骨干教师', '省青年教学新秀'],
    isFeatured: false,
    status: 'published',
    viewCount: 1320,
    createdAt: new Date('2023-09-01'),
    updatedAt: new Date('2024-06-10'),
  },
  {
    id: 'tb008',
    name: '孙教授',
    department: '机械工程学院',
    title: '教授',
    type: 'award-winning',
    avatar: '/placeholder.svg?height=120&width=120',
    introduction: '全国技术能手，在数控加工和智能制造领域具有深厚的理论功底和丰富的实践经验。',
    researchFields: ['数控加工', '智能制造', '精密测量'],
    achievements: ['全国技术能手', '主持教改项目5项', '发明专利8项'],
    courses: ['数控加工技术', '精密测量', '智能制造系统'],
    awards: ['全国技术能手', '省级技能大师', '省教学成果一等奖'],
    isFeatured: true,
    status: 'published',
    viewCount: 2100,
    createdAt: new Date('2023-09-15'),
    updatedAt: new Date('2024-06-20'),
  },
  {
    id: 'tb009',
    name: '周讲师',
    department: '艺术设计学院',
    title: '讲师',
    type: 'dual-qualified',
    avatar: '/placeholder.svg?height=120&width=120',
    introduction: '双师型教师，曾在知名设计公司担任设计总监，作品多次获得国内外设计奖项。',
    researchFields: ['品牌设计', 'UI/UX设计', '文创设计'],
    achievements: ['获红点设计奖1项', '主导品牌设计项目50余个', '出版设计教材2部'],
    courses: ['品牌设计', 'UI设计', '文创产品设计'],
    awards: ['双师型教师', '校教学能手', '优秀指导教师'],
    isFeatured: false,
    status: 'published',
    viewCount: 1180,
    createdAt: new Date('2023-10-01'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'tb010',
    name: '吴副教授',
    department: '信息工程学院',
    title: '副教授',
    type: 'teaching-master',
    avatar: '/placeholder.svg?height=120&width=120',
    introduction: '省级教学名师，计算机网络技术专业带头人，在网络安全和云计算领域具有丰富的教学和研究经验。',
    researchFields: ['网络安全', '云计算', '网络工程'],
    achievements: ['主持国家级课题1项', '发表SCI论文12篇', '获省级教学成果二等奖'],
    courses: ['网络安全', '云计算技术', '网络工程'],
    awards: ['省级教学名师', '省科技进步三等奖', '校优秀教师'],
    isFeatured: true,
    status: 'published',
    viewCount: 1850,
    createdAt: new Date('2023-10-15'),
    updatedAt: new Date('2024-06-18'),
  },"""

pattern = r"(export const teacherBrands: TeacherBrand\[\] = \[.*?)(\n\])"
match = re.search(pattern, content, re.DOTALL)
if match:
    insert_pos = match.start(2)
    content = content[:insert_pos] + teacherbrands_extra + content[insert_pos:]

# cultureBrands 补充（6条）
culturebrands_extra = """
  {
    id: 'cb005',
    name: '红色基因传承工程',
    type: 'case',
    description: '挖掘学校红色校史资源，将革命传统教育融入思政课程，打造具有校本特色的思政教育品牌。',
    content: '学校前身可追溯至抗战时期的技工学校，具有深厚的红色基因。通过走访老校友、整理校史档案、建设校史馆等方式，将革命传统教育有机融入思政课程，引导学生传承红色基因、赓续精神血脉。',
    images: ['/placeholder.svg?height=300&width=400'],
    coverImage: '/placeholder.svg?height=200&width=300',
    relatedMajor: '全校通用',
    status: 'published',
    viewCount: 1680,
    createdAt: new Date('2024-06-01'),
    updatedAt: new Date('2024-06-20'),
  },
  {
    id: 'cb006',
    name: '劳动教育实践基地',
    type: 'resource',
    description: '建设校内劳动教育实践基地，开展农耕体验、手工制作、志愿服务等劳动教育活动。',
    content: '依托学校周边的农田和社区资源，建立劳动教育实践基地。学生通过参与农作物种植、传统手工艺制作、社区志愿服务等劳动实践活动，培养劳动意识和劳动技能。基地已接待学生5000余人次。',
    images: ['/placeholder.svg?height=300&width=400'],
    coverImage: '/placeholder.svg?height=200&width=300',
    relatedMajor: '全校通用',
    status: 'published',
    viewCount: 1120,
    createdAt: new Date('2024-06-10'),
    updatedAt: new Date('2024-06-18'),
  },
  {
    id: 'cb007',
    name: '非遗文化进校园',
    type: 'activity',
    description: '邀请非遗传承人进校园，开展苏绣、昆曲、评弹等传统文化体验活动，弘扬中华优秀传统文化。',
    content: '每学期邀请2-3位非遗传承人进校园，开展为期一周的传统文化体验活动。学生可以亲手体验苏绣刺绣、学习昆曲身段、聆听评弹演唱，在沉浸式体验中感受传统文化的魅力。',
    images: ['/placeholder.svg?height=300&width=400', '/placeholder.svg?height=300&width=400'],
    coverImage: '/placeholder.svg?height=200&width=300',
    status: 'published',
    viewCount: 1980,
    createdAt: new Date('2024-06-15'),
    updatedAt: new Date('2024-06-22'),
  },
  {
    id: 'cb008',
    name: '志愿服务品牌项目',
    type: 'award',
    description: '学校志愿服务团队获评省级优秀志愿服务组织，累计服务时长超10万小时。',
    content: '学校青年志愿者协会成立于2005年，现有注册志愿者3000余人。团队长期开展社区服务、环保宣传、支教助学、助老助残等志愿服务活动，累计服务时长超10万小时，受益群众超5万人次。',
    images: ['/placeholder.svg?height=300&width=400'],
    coverImage: '/placeholder.svg?height=200&width=300',
    relatedMajor: '全校通用',
    status: 'published',
    viewCount: 1450,
    createdAt: new Date('2024-06-20'),
    updatedAt: new Date('2024-06-25'),
  },
  {
    id: 'cb009',
    name: '心理健康教育月',
    type: 'activity',
    description: '每年5月开展心理健康教育月活动，通过讲座、工作坊、心理剧等形式普及心理健康知识。',
    content: '心理健康教育月已连续举办15届，活动内容包括心理健康讲座、团体心理辅导、心理剧展演、心理漫画比赛等。活动期间心理咨询中心开放日接待学生咨询500余人次。',
    images: ['/placeholder.svg?height=300&width=400'],
    coverImage: '/placeholder.svg?height=200&width=300',
    status: 'published',
    viewCount: 1320,
    createdAt: new Date('2024-06-25'),
    updatedAt: new Date('2024-06-28'),
  },
  {
    id: 'cb010',
    name: '工匠精神培育计划',
    type: 'case',
    description: '通过技能大师工作室、工匠讲堂、技能竞赛等载体，系统培育学生工匠精神。',
    content: '聘请省级技能大师担任工作室负责人，定期开展工匠讲堂和技能实训。学生在技能大师指导下参加各级各类技能竞赛，近三年获国家级奖项15项、省级奖项80余项。',
    images: ['/placeholder.svg?height=300&width=400'],
    coverImage: '/placeholder.svg?height=200&width=300',
    relatedMajor: '全校通用',
    status: 'published',
    viewCount: 1780,
    createdAt: new Date('2024-06-28'),
    updatedAt: new Date('2024-06-30'),
  },"""

pattern = r"(export const cultureBrands: CultureBrand\[\] = \[.*?)(\n\])"
match = re.search(pattern, content, re.DOTALL)
if match:
    insert_pos = match.start(2)
    content = content[:insert_pos] + culturebrands_extra + content[insert_pos:]

# brandTopics 补充（4条）
topics_extra = """
  {
    id: 'bt003',
    name: '产教融合十周年纪念',
    theme: '校企合作',
    description: '回顾学校产教融合十年发展历程，展示校企合作的丰硕成果和典型案例。',
    coverImage: '/placeholder.svg?height=400&width=800',
    layout: 'timeline',
    content: [
      { type: 'text', title: '十年历程', content: '从2014年到2024年，学校产教融合经历了从探索到深化的发展历程...' },
      { type: 'image', content: '/placeholder.svg?height=300&width=500' },
      { type: 'video', content: 'https://example.com/video/anniversary' },
    ],
    relatedBrands: [
      { type: 'partner', ids: ['p001', 'p002', 'p009', 'p013'] },
      { type: 'talent', ids: ['tp001', 'tp007', 'tp010'] },
    ],
    isRecommended: false,
    status: 'published',
    viewCount: 1980,
    createdAt: new Date('2024-04-01'),
    updatedAt: new Date('2024-06-10'),
  },
  {
    id: 'bt004',
    name: '技能大赛获奖作品展',
    theme: '技能成才',
    description: '展示学校师生在各级各类技能竞赛中的获奖作品和精彩瞬间。',
    coverImage: '/placeholder.svg?height=400&width=800',
    layout: 'grid',
    content: [
      { type: 'text', title: '竞赛风采', content: '近三年学校师生在国家级、省级技能竞赛中屡获佳绩...' },
      { type: 'image', content: '/placeholder.svg?height=300&width=500' },
      { type: 'image', content: '/placeholder.svg?height=300&width=500' },
    ],
    relatedBrands: [
      { type: 'teacher', ids: ['tb001', 'tb004', 'tb008'] },
      { type: 'culture', ids: ['cb010'] },
    ],
    isRecommended: true,
    status: 'published',
    viewCount: 2450,
    createdAt: new Date('2024-05-01'),
    updatedAt: new Date('2024-06-15'),
  },
  {
    id: 'bt005',
    name: '创新创业成果展',
    theme: '创新创业',
    description: '展示学生创新创业项目的孵化成果和创业故事。',
    coverImage: '/placeholder.svg?height=400&width=800',
    layout: 'magazine',
    content: [
      { type: 'text', title: '创业故事', content: '学校创新创业孵化平台已培育创业项目200余个...' },
      { type: 'image', content: '/placeholder.svg?height=300&width=500' },
      { type: 'link', content: 'https://example.com/innovation' },
    ],
    relatedBrands: [
      { type: 'partner', ids: ['p004', 'p011'] },
      { type: 'talent', ids: ['tp011'] },
    ],
    isRecommended: false,
    status: 'draft',
    viewCount: 890,
    createdAt: new Date('2024-06-01'),
    updatedAt: new Date('2024-06-20'),
  },
  {
    id: 'bt006',
    name: '非遗文化传承专题',
    theme: '文化传承',
    description: '展示学校在非遗文化传承方面的教育实践和成果。',
    coverImage: '/placeholder.svg?height=400&width=800',
    layout: 'grid',
    content: [
      { type: 'text', title: '传承之路', content: '学校积极开展非遗文化进校园活动...' },
      { type: 'image', content: '/placeholder.svg?height=300&width=500' },
      { type: 'video', content: 'https://example.com/heritage' },
    ],
    relatedBrands: [
      { type: 'culture', ids: ['cb007', 'cb009'] },
    ],
    isRecommended: false,
    status: 'published',
    viewCount: 1560,
    createdAt: new Date('2024-06-10'),
    updatedAt: new Date('2024-06-25'),
  },"""

pattern = r"(export const brandTopics: BrandTopic\[\] = \[.*?)(\n\])"
match = re.search(pattern, content, re.DOTALL)
if match:
    insert_pos = match.start(2)
    content = content[:insert_pos] + topics_extra + content[insert_pos:]

with open('lib/mock-data.ts', 'w', encoding='utf-8') as f:
    f.write(content)

print("Batch 2 done: talentProfiles +10, employmentCases +7, jobBrands +6, majorBrands +6, teacherBrands +6, cultureBrands +6, brandTopics +4")
