import re

with open('lib/mock-data.ts', 'r', encoding='utf-8') as f:
    content = f.read()

# jobs 补充（9条）
jobs_extra = """
  {
    id: 'job007',
    title: '电商运营专员',
    partnerId: 'p012',
    partnerName: '江苏省电子商务协会成员单位',
    partnerLogo: '/placeholder.svg?height=64&width=64',
    type: 'full-time',
    workNature: 'on-site',
    department: '运营部',
    location: '江苏省南京市建邺区',
    salaryMin: 6000,
    salaryMax: 12000,
    salaryUnit: 'month',
    requirements: [
      '电子商务、市场营销等相关专业大专及以上学历',
      '熟悉主流电商平台运营规则',
      '具备良好的数据分析能力',
      '有直播运营经验者优先',
    ],
    responsibilities: [
      '负责电商平台的日常运营管理',
      '策划和执行店铺促销活动',
      '分析运营数据，优化运营策略',
      '维护客户关系，处理售后问题',
    ],
    benefits: ['五险一金', '绩效奖金', '带薪年假', '员工培训'],
    education: '大专',
    experience: '应届生',
    headcount: 10,
    suitableMajors: ['电子商务', '市场营销', '工商管理'],
    skills: ['电商平台运营', '数据分析', '营销策划', '客户服务'],
    description: '我们正在寻找热爱电商行业的运营人才。公司提供系统的电商运营培训，帮助新人快速成长为运营专家。',
    contactPerson: '钱主任',
    contactPhone: '12800128012',
    contactEmail: 'hr@jseca.org',
    status: 'published',
    isUrgent: false,
    isRecommended: true,
    viewCount: 1850,
    applicationCount: 56,
    deadline: new Date('2024-12-31'),
    createdAt: new Date('2024-06-20'),
    updatedAt: new Date('2024-06-25'),
  },
  {
    id: 'job008',
    title: '生物医药检测员',
    partnerId: 'p009',
    partnerName: '南京生物医药有限公司',
    partnerLogo: '/placeholder.svg?height=64&width=64',
    type: 'full-time',
    workNature: 'on-site',
    department: '质量检测部',
    location: '江苏省南京市江宁区',
    salaryMin: 8000,
    salaryMax: 15000,
    salaryUnit: 'month',
    requirements: [
      '药学、生物技术、化学等相关专业本科及以上学历',
      '熟悉HPLC、GC等分析仪器的操作',
      '了解GMP规范和药品质量标准',
      '有药品检测实习经验者优先',
    ],
    responsibilities: [
      '负责原料、中间体和成品的质量检测',
      '操作和维护分析仪器设备',
      '编写检测记录和检验报告',
      '参与质量标准和方法的验证工作',
    ],
    benefits: ['五险一金', '年终奖金', '带薪年假', '免费午餐', '住房补贴'],
    education: '本科',
    experience: '应届生',
    headcount: 5,
    suitableMajors: ['药学', '生物技术', '化学工程'],
    skills: ['HPLC', 'GC', '药物分析', 'GMP', '质量检测'],
    description: '加入我们的质量检测团队，参与新药研发全过程的质量保障工作。公司提供完善的职业发展和技能培训。',
    contactPerson: '吴总监',
    contactPhone: '13100131009',
    contactEmail: 'hr@njbiomed.com',
    status: 'published',
    isUrgent: true,
    isRecommended: false,
    viewCount: 720,
    applicationCount: 23,
    deadline: new Date('2024-11-30'),
    createdAt: new Date('2024-06-22'),
    updatedAt: new Date('2024-06-28'),
  },
  {
    id: 'job009',
    title: '软件测试工程师',
    partnerId: 'p013',
    partnerName: '南京软件谷入驻企业',
    partnerLogo: '/placeholder.svg?height=64&width=64',
    type: 'full-time',
    workNature: 'hybrid',
    department: '测试部',
    location: '江苏省南京市雨花台区',
    salaryMin: 9000,
    salaryMax: 16000,
    salaryUnit: 'month',
    requirements: [
      '计算机相关专业大专及以上学历',
      '熟悉软件测试理论和方法',
      '了解自动化测试工具和框架',
      '有测试实习经验者优先',
    ],
    responsibilities: [
      '参与软件产品的功能测试和性能测试',
      '编写测试用例和执行测试计划',
      '记录和跟踪软件缺陷',
      '编写自动化测试脚本',
    ],
    benefits: ['五险一金', '弹性工作', '远程办公', '技术培训', '晋升通道'],
    education: '大专',
    experience: '应届生',
    headcount: 6,
    suitableMajors: ['软件技术', '计算机应用技术', '人工智能应用技术'],
    skills: ['软件测试', '自动化测试', 'Selenium', 'Python', 'SQL'],
    description: '我们正在寻找细心负责的软件测试工程师。公司提供专业的测试培训和清晰的职业发展路径。',
    contactPerson: '李总监',
    contactPhone: '12700127013',
    contactEmail: 'hr@njsoftwarevalley.com',
    status: 'published',
    isUrgent: false,
    isRecommended: true,
    viewCount: 1450,
    applicationCount: 42,
    deadline: new Date('2024-12-31'),
    createdAt: new Date('2024-06-25'),
    updatedAt: new Date('2024-06-30'),
  },
  {
    id: 'job010',
    title: '文创产品设计师',
    partnerId: 'p011',
    partnerName: '苏州文化创意集团',
    partnerLogo: '/placeholder.svg?height=64&width=64',
    type: 'full-time',
    workNature: 'on-site',
    department: '设计部',
    location: '江苏省苏州市姑苏区',
    salaryMin: 7000,
    salaryMax: 14000,
    salaryUnit: 'month',
    requirements: [
      '设计类相关专业本科及以上学历',
      '熟练使用PS、AI、C4D等设计软件',
      '具备扎实的手绘能力和创意思维',
      '有文创产品设计经验者优先',
    ],
    responsibilities: [
      '负责文创产品的创意设计和视觉呈现',
      '参与产品策划和市场调研',
      '完成产品打样和工艺跟进',
      '维护设计素材库和品牌视觉规范',
    ],
    benefits: ['五险一金', '创意奖金', '带薪年假', '设计展会参观'],
    education: '本科',
    experience: '应届生',
    headcount: 3,
    suitableMajors: ['视觉传达', '产品设计', '动画设计'],
    skills: ['Photoshop', 'Illustrator', 'C4D', '手绘', '品牌设计'],
    description: '加入我们的创意设计团队，将传统文化元素转化为受欢迎的文创产品。公司鼓励创新，提供宽松的设计氛围。',
    contactPerson: '孙总监',
    contactPhone: '12900129011',
    contactEmail: 'hr@szccg.com',
    status: 'published',
    isUrgent: false,
    isRecommended: false,
    viewCount: 980,
    applicationCount: 18,
    deadline: new Date('2024-12-31'),
    createdAt: new Date('2024-06-28'),
    updatedAt: new Date('2024-06-30'),
  },
  {
    id: 'job011',
    title: '智能制造技术员',
    partnerId: 'p014',
    partnerName: '无锡智能制造装备有限公司',
    partnerLogo: '/placeholder.svg?height=64&width=64',
    type: 'full-time',
    workNature: 'on-site',
    department: '技术部',
    location: '江苏省无锡市新吴区',
    salaryMin: 8000,
    salaryMax: 13000,
    salaryUnit: 'month',
    requirements: [
      '机电一体化、智能制造等相关专业',
      '熟悉PLC编程和工业机器人操作',
      '了解机器视觉和自动化控制原理',
      '有项目实习经验者优先',
    ],
    responsibilities: [
      '负责自动化设备的安装调试和维护',
      '编写PLC程序和机器人示教程序',
      '参与自动化产线的设计和优化',
      '解决生产现场的技术问题',
    ],
    benefits: ['五险一金', '包吃包住', '技能补贴', '晋升培训'],
    education: '大专',
    experience: '应届生',
    headcount: 8,
    suitableMajors: ['智能制造技术', '机电一体化', '工业机器人技术'],
    skills: ['PLC编程', '工业机器人', '机器视觉', '电气调试'],
    description: '加入我们的技术团队，参与前沿智能制造装备的研发和应用。公司提供系统的技术培训和广阔的发展空间。',
    contactPerson: '周总监',
    contactPhone: '12600126014',
    contactEmail: 'hr@wxim.com',
    status: 'published',
    isUrgent: true,
    isRecommended: true,
    viewCount: 1120,
    applicationCount: 35,
    deadline: new Date('2024-11-30'),
    createdAt: new Date('2024-06-30'),
    updatedAt: new Date('2024-06-30'),
  },
  {
    id: 'job012',
    title: '现代物流专员',
    partnerId: 'p008',
    partnerName: '长三角现代服务业联合会',
    partnerLogo: '/placeholder.svg?height=64&width=64',
    type: 'full-time',
    workNature: 'on-site',
    department: '物流运营部',
    location: '江苏省南京市',
    salaryMin: 6000,
    salaryMax: 10000,
    salaryUnit: 'month',
    requirements: [
      '物流管理、供应链管理等相关专业',
      '熟悉物流运营流程和仓储管理',
      '具备数据分析能力和成本意识',
      '有物流实习经验者优先',
    ],
    responsibilities: [
      '负责物流订单的接收、处理和跟踪',
      '协调仓储、运输等物流资源',
      '分析物流数据，优化配送路线',
      '处理物流异常和客户投诉',
    ],
    benefits: ['五险一金', '绩效奖金', '带薪年假', '员工旅游'],
    education: '大专',
    experience: '应届生',
    headcount: 5,
    suitableMajors: ['物流管理', '供应链管理', '工商管理'],
    skills: ['物流管理', '仓储管理', '数据分析', 'ERP系统'],
    description: '我们正在寻找对物流行业充满热情的人才。公司提供完善的培训和广阔的晋升空间。',
    contactPerson: '周主任',
    contactPhone: '13200132008',
    contactEmail: 'hr@csjmsba.org',
    status: 'published',
    isUrgent: false,
    isRecommended: false,
    viewCount: 680,
    applicationCount: 15,
    deadline: new Date('2024-12-31'),
    createdAt: new Date('2024-06-15'),
    updatedAt: new Date('2024-06-20'),
  },
  {
    id: 'job013',
    title: '云计算运维实习生',
    partnerId: 'p006',
    partnerName: '上海云智科技股份有限公司',
    partnerLogo: '/placeholder.svg?height=64&width=64',
    type: 'internship',
    workNature: 'hybrid',
    department: '云平台部',
    location: '上海市浦东新区',
    salaryMin: 4000,
    salaryMax: 6000,
    salaryUnit: 'month',
    requirements: [
      '计算机相关专业在读学生',
      '熟悉Linux系统和Shell脚本',
      '了解Docker、Kubernetes等容器技术',
      '能够实习6个月以上',
    ],
    responsibilities: [
      '协助云平台的日常运维和监控',
      '参与自动化运维工具的开发',
      '处理云资源申请和配置变更',
      '编写运维文档和操作手册',
    ],
    benefits: ['实习补贴', '转正机会', '技术培训', '弹性工作'],
    education: '大专',
    experience: '在校生',
    headcount: 4,
    suitableMajors: ['云计算技术', '软件技术', '网络工程'],
    skills: ['Linux', 'Docker', 'Kubernetes', 'Shell', 'Python'],
    description: '实习期间表现优秀者可获得转正机会。公司技术氛围浓厚，是学习和成长的绝佳平台。',
    contactPerson: '赵HR',
    contactPhone: '13400134006',
    contactEmail: 'hr@shyztech.com',
    status: 'published',
    isUrgent: false,
    isRecommended: false,
    viewCount: 890,
    applicationCount: 22,
    deadline: new Date('2024-10-31'),
    createdAt: new Date('2024-06-18'),
    updatedAt: new Date('2024-06-25'),
  },
  {
    id: 'job014',
    title: '大数据开发工程师',
    partnerId: 'p001',
    partnerName: '苏州智联科技有限公司',
    partnerLogo: '/placeholder.svg?height=64&width=64',
    type: 'full-time',
    workNature: 'on-site',
    department: '数据平台部',
    location: '江苏省苏州市工业园区',
    salaryMin: 15000,
    salaryMax: 25000,
    salaryUnit: 'month',
    requirements: [
      '计算机、数学等相关专业本科及以上学历',
      '熟悉Hadoop、Spark等大数据技术栈',
      '熟练使用SQL和Python进行数据处理',
      '有大数据项目经验者优先',
    ],
    responsibilities: [
      '负责大数据平台的开发和维护',
      '设计和优化数据仓库模型',
      '开发数据ETL流程和数据管道',
      '保障数据质量和系统稳定性',
    ],
    benefits: ['五险一金', '年终奖金', '带薪年假', '技术培训', '股票期权'],
    education: '本科',
    experience: '1-3年',
    headcount: 3,
    suitableMajors: ['大数据技术', '计算机科学', '软件工程'],
    skills: ['Hadoop', 'Spark', 'SQL', 'Python', '数据仓库'],
    description: '我们正在寻找热爱大数据技术的开发工程师。公司数据规模庞大，技术挑战多，是技术成长的绝佳平台。',
    contactPerson: '张HR',
    contactPhone: '13800138001',
    contactEmail: 'hr@zltech.com',
    status: 'published',
    isUrgent: true,
    isRecommended: true,
    viewCount: 1680,
    applicationCount: 48,
    deadline: new Date('2024-12-31'),
    createdAt: new Date('2024-06-20'),
    updatedAt: new Date('2024-06-28'),
  },
  {
    id: 'job015',
    title: '网络安全工程师',
    partnerId: 'p001',
    partnerName: '苏州智联科技有限公司',
    partnerLogo: '/placeholder.svg?height=64&width=64',
    type: 'full-time',
    workNature: 'on-site',
    department: '安全部',
    location: '江苏省苏州市工业园区',
    salaryMin: 18000,
    salaryMax: 30000,
    salaryUnit: 'month',
    requirements: [
      '网络安全、计算机等相关专业本科及以上学历',
      '熟悉渗透测试、漏洞挖掘等安全技术',
      '了解常见安全设备和防护方案',
      '持有CISP、CISSP等证书者优先',
    ],
    responsibilities: [
      '负责公司网络和系统的安全防护',
      '开展渗透测试和安全评估',
      '制定安全策略和应急预案',
      '处理安全事件和应急响应',
    ],
    benefits: ['五险一金', '高额奖金', '带薪年假', '专业培训', '晋升通道'],
    education: '本科',
    experience: '1-3年',
    headcount: 2,
    suitableMajors: ['网络安全', '信息安全', '计算机科学'],
    skills: ['渗透测试', '漏洞挖掘', '安全策略', '应急响应', 'Python'],
    description: '我们正在寻找具备专业安全技能的网络安全工程师。公司高度重视信息安全，提供完善的职业发展通道。',
    contactPerson: '张HR',
    contactPhone: '13800138001',
    contactEmail: 'hr@zltech.com',
    status: 'published',
    isUrgent: false,
    isRecommended: true,
    viewCount: 1250,
    applicationCount: 19,
    deadline: new Date('2024-12-31'),
    createdAt: new Date('2024-06-22'),
    updatedAt: new Date('2024-06-28'),
  },"""

pattern = r"(export const jobs: Job\[\] = \[.*?)(\n\])"
match = re.search(pattern, content, re.DOTALL)
if match:
    insert_pos = match.start(2)
    content = content[:insert_pos] + jobs_extra + content[insert_pos:]

# studentProfiles 补充（9条）
students_extra = """
  {
    id: 'stu004',
    name: '赵静雯',
    gender: 'female',
    avatar: '/placeholder.svg?height=80&width=80',
    major: '软件技术',
    department: '信息工程学院',
    grade: '2021级',
    studentId: 'S2021015',
    phone: '13812345004',
    email: 'zhaojingwen@student.hdvtc.edu.cn',
    expectedSalary: '12-18K',
    expectedLocation: '苏州、上海',
    skills: ['React', 'TypeScript', 'UI设计', 'JavaScript'],
    certificates: ['计算机等级证书', '前端开发工程师认证'],
    internshipExperience: '曾在苏州智联科技实习3个月，参与前端组件库开发',
    selfIntroduction: '热爱前端开发，关注用户体验，在校期间多次获得设计类奖项。',
    resumeUrl: '/placeholder.pdf',
    status: 'seeking',
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-06-18'),
  },
  {
    id: 'stu005',
    name: '孙浩然',
    gender: 'male',
    avatar: '/placeholder.svg?height=80&width=80',
    major: '智能制造技术',
    department: '机械工程学院',
    grade: '2021级',
    studentId: 'S2021045',
    phone: '13812345005',
    email: 'sunhaoran@student.hdvtc.edu.cn',
    expectedSalary: '9-13K',
    expectedLocation: '杭州、苏州',
    skills: ['CAD设计', '数控加工', 'PLC编程', '机械基础'],
    certificates: ['数控车工中级', 'CAD制图员'],
    internshipExperience: '在杭州智能制造有限公司实习4个月，参与数控编程和设备调试',
    selfIntroduction: '对机械制造有浓厚兴趣，具备扎实的专业技能和动手能力。',
    resumeUrl: '/placeholder.pdf',
    status: 'seeking',
    createdAt: new Date('2024-03-10'),
    updatedAt: new Date('2024-06-15'),
  },
  {
    id: 'stu006',
    name: '周晓峰',
    gender: 'male',
    avatar: '/placeholder.svg?height=80&width=80',
    major: '新能源技术',
    department: '新能源学院',
    grade: '2022级',
    studentId: 'S2022025',
    phone: '13812345006',
    email: 'zhouxiaofeng@student.hdvtc.edu.cn',
    expectedSalary: '8-12K',
    expectedLocation: '南京、苏州',
    skills: ['光伏技术', '电力电子', '储能系统', '设备运维'],
    certificates: ['电工证', '光伏运维工程师'],
    internshipExperience: '在江苏新能源集团实训基地学习2个月',
    selfIntroduction: '对新能源技术有深入研究，希望在该领域长期发展。',
    resumeUrl: '/placeholder.pdf',
    status: 'seeking',
    createdAt: new Date('2024-03-15'),
    updatedAt: new Date('2024-06-10'),
  },
  {
    id: 'stu007',
    name: '林小雅',
    gender: 'female',
    avatar: '/placeholder.svg?height=80&width=80',
    major: '大数据技术',
    department: '信息工程学院',
    grade: '2022级',
    studentId: 'S2022038',
    phone: '13812345007',
    email: 'linxiaoya@student.hdvtc.edu.cn',
    expectedSalary: '10-15K',
    expectedLocation: '苏州、上海、杭州',
    skills: ['SQL', 'Python', '数据可视化', 'Hadoop', 'Excel'],
    certificates: ['计算机等级证书', '数据分析师认证'],
    internshipExperience: '曾在苏州智联科技实习2个月，参与数据分析项目',
    selfIntroduction: '对数据分析充满热情，善于从数据中发现业务价值。',
    resumeUrl: '/placeholder.pdf',
    status: 'seeking',
    createdAt: new Date('2024-03-20'),
    updatedAt: new Date('2024-06-08'),
  },
  {
    id: 'stu008',
    name: '吴志远',
    gender: 'male',
    avatar: '/placeholder.svg?height=80&width=80',
    major: '人工智能应用技术',
    department: '信息工程学院',
    grade: '2021级',
    studentId: 'S2021050',
    phone: '13812345008',
    email: 'wuzhiyuan@student.hdvtc.edu.cn',
    expectedSalary: '18-25K',
    expectedLocation: '上海、苏州',
    skills: ['NLP', '知识图谱', 'PyTorch', 'Python', '算法优化'],
    certificates: ['计算机等级证书', 'AI开发者认证', '英语六级'],
    internshipExperience: '在上海云智科技实习6个月，参与NLP项目研发',
    selfIntroduction: '专注于自然语言处理方向，发表学术论文2篇。',
    resumeUrl: '/placeholder.pdf',
    status: 'seeking',
    createdAt: new Date('2024-03-25'),
    updatedAt: new Date('2024-06-22'),
  },
  {
    id: 'stu009',
    name: '郑欣怡',
    gender: 'female',
    avatar: '/placeholder.svg?height=80&width=80',
    major: '电子商务',
    department: '商学院',
    grade: '2022级',
    studentId: 'S2022042',
    phone: '13812345009',
    email: 'zhengxinyi@student.hdvtc.edu.cn',
    expectedSalary: '6-12K',
    expectedLocation: '南京、苏州',
    skills: ['电商运营', '直播带货', '数据分析', '营销策划'],
    certificates: ['电子商务师', '直播运营师'],
    internshipExperience: '运营个人电商账号，月销售额达5万元',
    selfIntroduction: '对电商运营有实战经验，善于把握市场趋势。',
    resumeUrl: '/placeholder.pdf',
    status: 'seeking',
    createdAt: new Date('2024-04-01'),
    updatedAt: new Date('2024-06-15'),
  },
  {
    id: 'stu010',
    name: '王鹏飞',
    gender: 'male',
    avatar: '/placeholder.svg?height=80&width=80',
    major: '新能源技术',
    department: '新能源学院',
    grade: '2021级',
    studentId: 'S2021060',
    phone: '13812345010',
    email: 'wangpengfei@student.hdvtc.edu.cn',
    expectedSalary: '10-15K',
    expectedLocation: '南京、无锡',
    skills: ['风电技术', '电网调度', '设备维护', '电力系统'],
    certificates: ['电工证', '风电运维工程师', '高压电工证'],
    internshipExperience: '在江苏新能源集团风电场实习3个月',
    selfIntroduction: '对风电技术有深入研究，具备扎实的专业基础和动手能力。',
    resumeUrl: '/placeholder.pdf',
    status: 'seeking',
    createdAt: new Date('2024-04-05'),
    updatedAt: new Date('2024-06-12'),
  },
  {
    id: 'stu011',
    name: '黄嘉琪',
    gender: 'female',
    avatar: '/placeholder.svg?height=80&width=80',
    major: '软件技术',
    department: '信息工程学院',
    grade: '2022级',
    studentId: 'S2022055',
    phone: '13812345011',
    email: 'huangjiaqi@student.hdvtc.edu.cn',
    expectedSalary: '10-15K',
    expectedLocation: '苏州、上海',
    skills: ['Java', 'Spring Boot', 'MySQL', 'Redis', 'Vue'],
    certificates: ['计算机等级证书', '软件设计师'],
    internshipExperience: '曾在校内工作室参与项目开发',
    selfIntroduction: '热爱编程，具备扎实的Java后端开发能力。',
    resumeUrl: '/placeholder.pdf',
    status: 'seeking',
    createdAt: new Date('2024-04-10'),
    updatedAt: new Date('2024-06-08'),
  },
  {
    id: 'stu012',
    name: '刘思远',
    gender: 'male',
    avatar: '/placeholder.svg?height=80&width=80',
    major: '智能制造技术',
    department: '机械工程学院',
    grade: '2021级',
    studentId: 'S2021070',
    phone: '13812345012',
    email: 'liusiyuan@student.hdvtc.edu.cn',
    expectedSalary: '11-16K',
    expectedLocation: '无锡、苏州',
    skills: ['工业机器人', '机器视觉', '自动化集成', 'PLC编程'],
    certificates: ['工业机器人操作证', '电工证'],
    internshipExperience: '在无锡智能制造装备有限公司实习5个月，参与自动化项目',
    selfIntroduction: '对自动化技术有深入研究，希望从事智能制造相关工作。',
    resumeUrl: '/placeholder.pdf',
    status: 'seeking',
    createdAt: new Date('2024-04-15'),
    updatedAt: new Date('2024-06-20'),
  },"""

pattern = r"(export const studentProfiles: StudentProfile\[\] = \[.*?)(\n\])"
match = re.search(pattern, content, re.DOTALL)
if match:
    insert_pos = match.start(2)
    content = content[:insert_pos] + students_extra + content[insert_pos:]

# jobApplications 补充（15条）
applications_extra = """
  {
    id: 'app006',
    jobId: 'job007',
    jobTitle: '电商运营专员',
    partnerId: 'p012',
    partnerName: '江苏省电子商务协会成员单位',
    studentId: 'stu009',
    studentName: '郑欣怡',
    studentMajor: '电子商务',
    studentPhone: '13812345009',
    studentEmail: 'zhengxinyi@student.hdvtc.edu.cn',
    resumeUrl: '/placeholder.pdf',
    coverLetter: '我具有丰富的电商运营实战经验，曾运营个人店铺月销售额达5万元，希望能加入贵公司。',
    status: 'interview',
    interviewTime: new Date('2024-07-10 10:00'),
    interviewLocation: '南京市建邺区河西CBD',
    appliedAt: new Date('2024-06-28'),
    updatedAt: new Date('2024-07-02'),
  },
  {
    id: 'app007',
    jobId: 'job008',
    jobTitle: '生物医药检测员',
    partnerId: 'p009',
    partnerName: '南京生物医药有限公司',
    studentId: 'stu004',
    studentName: '赵静雯',
    studentMajor: '软件技术',
    studentPhone: '13812345004',
    studentEmail: 'zhaojingwen@student.hdvtc.edu.cn',
    resumeUrl: '/placeholder.pdf',
    status: 'rejected',
    feedback: '专业背景与岗位要求不太匹配',
    appliedAt: new Date('2024-06-25'),
    updatedAt: new Date('2024-06-28'),
  },
  {
    id: 'app008',
    jobId: 'job009',
    jobTitle: '软件测试工程师',
    partnerId: 'p013',
    partnerName: '南京软件谷入驻企业',
    studentId: 'stu011',
    studentName: '黄嘉琪',
    studentMajor: '软件技术',
    studentPhone: '13812345011',
    studentEmail: 'huangjiaqi@student.hdvtc.edu.cn',
    resumeUrl: '/placeholder.pdf',
    coverLetter: '我对软件测试有浓厚兴趣，具备良好的编程基础和细致的工作态度。',
    status: 'pending',
    appliedAt: new Date('2024-06-30'),
    updatedAt: new Date('2024-06-30'),
  },
  {
    id: 'app009',
    jobId: 'job010',
    jobTitle: '文创产品设计师',
    partnerId: 'p011',
    partnerName: '苏州文化创意集团',
    studentId: 'stu009',
    studentName: '郑欣怡',
    studentMajor: '电子商务',
    studentPhone: '13812345009',
    studentEmail: 'zhengxinyi@student.hdvtc.edu.cn',
    resumeUrl: '/placeholder.pdf',
    status: 'viewed',
    appliedAt: new Date('2024-06-28'),
    updatedAt: new Date('2024-06-29'),
  },
  {
    id: 'app010',
    jobId: 'job011',
    jobTitle: '智能制造技术员',
    partnerId: 'p014',
    partnerName: '无锡智能制造装备有限公司',
    studentId: 'stu012',
    studentName: '刘思远',
    studentMajor: '智能制造技术',
    studentPhone: '13812345012',
    studentEmail: 'liusiyuan@student.hdvtc.edu.cn',
    resumeUrl: '/placeholder.pdf',
    coverLetter: '我在校期间参与了多个自动化项目，具备扎实的PLC编程和机器人操作能力。',
    status: 'interview',
    interviewTime: new Date('2024-07-08 14:00'),
    interviewLocation: '无锡市新吴区智能制造产业园',
    appliedAt: new Date('2024-06-25'),
    updatedAt: new Date('2024-07-01'),
  },
  {
    id: 'app011',
    jobId: 'job012',
    jobTitle: '现代物流专员',
    partnerId: 'p008',
    partnerName: '长三角现代服务业联合会',
    studentId: 'stu009',
    studentName: '郑欣怡',
    studentMajor: '电子商务',
    studentPhone: '13812345009',
    studentEmail: 'zhengxinyi@student.hdvtc.edu.cn',
    resumeUrl: '/placeholder.pdf',
    status: 'pending',
    appliedAt: new Date('2024-06-30'),
    updatedAt: new Date('2024-06-30'),
  },
  {
    id: 'app012',
    jobId: 'job013',
    jobTitle: '云计算运维实习生',
    partnerId: 'p006',
    partnerName: '上海云智科技股份有限公司',
    studentId: 'stu007',
    studentName: '林小雅',
    studentMajor: '大数据技术',
    studentPhone: '13812345007',
    studentEmail: 'linxiaoya@student.hdvtc.edu.cn',
    resumeUrl: '/placeholder.pdf',
    coverLetter: '我对云计算技术充满热情，熟悉Linux和Docker，希望能获得实习机会。',
    status: 'offer',
    offerSalary: 5000,
    appliedAt: new Date('2024-06-20'),
    updatedAt: new Date('2024-06-28'),
  },
  {
    id: 'app013',
    jobId: 'job014',
    jobTitle: '大数据开发工程师',
    partnerId: 'p001',
    partnerName: '苏州智联科技有限公司',
    studentId: 'stu007',
    studentName: '林小雅',
    studentMajor: '大数据技术',
    studentPhone: '13812345007',
    studentEmail: 'linxiaoya@student.hdvtc.edu.cn',
    resumeUrl: '/placeholder.pdf',
    coverLetter: '我具备扎实的大数据技术基础，熟悉Hadoop和Spark生态，希望能加入贵公司的数据团队。',
    status: 'interview',
    interviewTime: new Date('2024-07-12 09:30'),
    interviewLocation: '苏州智联科技总部',
    appliedAt: new Date('2024-06-22'),
    updatedAt: new Date('2024-06-27'),
  },
  {
    id: 'app014',
    jobId: 'job015',
    jobTitle: '网络安全工程师',
    partnerId: 'p001',
    partnerName: '苏州智联科技有限公司',
    studentId: 'stu008',
    studentName: '吴志远',
    studentMajor: '人工智能应用技术',
    studentPhone: '13812345008',
    studentEmail: 'wuzhiyuan@student.hdvtc.edu.cn',
    resumeUrl: '/placeholder.pdf',
    status: 'viewed',
    appliedAt: new Date('2024-06-26'),
    updatedAt: new Date('2024-06-27'),
  },
  {
    id: 'app015',
    jobId: 'job001',
    jobTitle: 'AI算法工程师',
    partnerId: 'p001',
    partnerName: '苏州智联科技有限公司',
    studentId: 'stu008',
    studentName: '吴志远',
    studentMajor: '人工智能应用技术',
    studentPhone: '13812345008',
    studentEmail: 'wuzhiyuan@student.hdvtc.edu.cn',
    resumeUrl: '/placeholder.pdf',
    coverLetter: '我专注于NLP方向的研究，发表学术论文2篇，希望能加入贵公司的AI研发团队。',
    status: 'interview',
    interviewTime: new Date('2024-07-03 10:00'),
    interviewLocation: '苏州智联科技总部',
    appliedAt: new Date('2024-06-18'),
    updatedAt: new Date('2024-06-24'),
  },
  {
    id: 'app016',
    jobId: 'job002',
    jobTitle: 'Java开发工程师',
    partnerId: 'p001',
    partnerName: '苏州智联科技有限公司',
    studentId: 'stu011',
    studentName: '黄嘉琪',
    studentMajor: '软件技术',
    studentPhone: '13812345011',
    studentEmail: 'huangjiaqi@student.hdvtc.edu.cn',
    resumeUrl: '/placeholder.pdf',
    status: 'pending',
    appliedAt: new Date('2024-06-28'),
    updatedAt: new Date('2024-06-28'),
  },
  {
    id: 'app017',
    jobId: 'job003',
    jobTitle: '新能源技术实习生',
    partnerId: 'p002',
    partnerName: '江苏新能源集团',
    studentId: 'stu006',
    studentName: '周晓峰',
    studentMajor: '新能源技术',
    studentPhone: '13812345006',
    studentEmail: 'zhouxiaofeng@student.hdvtc.edu.cn',
    resumeUrl: '/placeholder.pdf',
    coverLetter: '我对新能源技术充满热情，希望能在贵公司实习并获得转正机会。',
    status: 'pending',
    appliedAt: new Date('2024-06-30'),
    updatedAt: new Date('2024-06-30'),
  },
  {
    id: 'app018',
    jobId: 'job004',
    jobTitle: '前端开发工程师',
    partnerId: 'p001',
    partnerName: '苏州智联科技有限公司',
    studentId: 'stu004',
    studentName: '赵静雯',
    studentMajor: '软件技术',
    studentPhone: '13812345004',
    studentEmail: 'zhaojingwen@student.hdvtc.edu.cn',
    resumeUrl: '/placeholder.pdf',
    coverLetter: '我具备扎实的前端开发能力，熟悉React和TypeScript，希望能加入贵公司前端团队。',
    status: 'offer',
    offerSalary: 15000,
    appliedAt: new Date('2024-06-20'),
    updatedAt: new Date('2024-06-28'),
  },
  {
    id: 'app019',
    jobId: 'job005',
    jobTitle: '工业机器人操作员',
    partnerId: 'p006',
    partnerName: '杭州智能制造有限公司',
    studentId: 'stu005',
    studentName: '孙浩然',
    studentMajor: '智能制造技术',
    studentPhone: '13812345005',
    studentEmail: 'sunhaoran@student.hdvtc.edu.cn',
    resumeUrl: '/placeholder.pdf',
    status: 'interview',
    interviewTime: new Date('2024-07-08 09:00'),
    interviewLocation: '杭州市萧山区',
    appliedAt: new Date('2024-06-22'),
    updatedAt: new Date('2024-06-26'),
  },
  {
    id: 'app020',
    jobId: 'job006',
    jobTitle: '数据分析师',
    partnerId: 'p001',
    partnerName: '苏州智联科技有限公司',
    studentId: 'stu007',
    studentName: '林小雅',
    studentMajor: '大数据技术',
    studentPhone: '13812345007',
    studentEmail: 'linxiaoya@student.hdvtc.edu.cn',
    resumeUrl: '/placeholder.pdf',
    status: 'viewed',
    appliedAt: new Date('2024-06-25'),
    updatedAt: new Date('2024-06-26'),
  },"""

pattern = r"(export const jobApplications: JobApplication\[\] = \[.*?)(\n\])"
match = re.search(pattern, content, re.DOTALL)
if match:
    insert_pos = match.start(2)
    content = content[:insert_pos] + applications_extra + content[insert_pos:]

# employmentProjects 补充（4条）
projects_extra = """
  {
    id: 'ep005',
    name: '2024年夏季实习生招募',
    type: '专场招聘',
    season: '2024夏',
    partnerIds: ['p001', 'p002', 'p009', 'p013'],
    targetStudents: '2025届在校生',
    startDate: new Date('2024-06-01'),
    endDate: new Date('2024-08-31'),
    status: 'ended',
    jobCount: 8,
    applicationCount: 156,
    description: '2024年夏季实习生招募活动已结束，共输送实习生120余人到各合作企业。',
    createdAt: new Date('2024-05-01'),
    updatedAt: new Date('2024-09-01'),
  },
  {
    id: 'ep006',
    name: '江苏新能源集团定向培养班',
    type: '定向招聘',
    season: '2024',
    partnerIds: ['p002'],
    targetStudents: '新能源学院2025届',
    startDate: new Date('2024-09-01'),
    endDate: new Date('2025-06-30'),
    status: 'ongoing',
    jobCount: 2,
    applicationCount: 45,
    description: '面向新能源学院2025届毕业生的定向培养项目，入选学生将接受企业定制化培养。',
    createdAt: new Date('2024-08-15'),
    updatedAt: new Date('2024-09-01'),
  },
  {
    id: 'ep007',
    name: '2025届毕业生春季双选会',
    type: 'spring',
    season: '2025春',
    partnerIds: ['p001', 'p002', 'p009', 'p011', 'p013', 'p014'],
    targetStudents: '2025届毕业生',
    startDate: new Date('2025-03-01'),
    endDate: new Date('2025-05-31'),
    status: 'preparing',
    jobCount: 10,
    applicationCount: 0,
    description: '2025届毕业生春季大型校园双选会正在筹备中，预计邀请100余家合作企业。',
    createdAt: new Date('2024-12-01'),
    updatedAt: new Date('2024-12-01'),
  },
  {
    id: 'ep008',
    name: '南京生物医药专场招聘',
    type: '专场招聘',
    season: '2024',
    partnerIds: ['p009'],
    targetStudents: '医学工程学院2025届',
    startDate: new Date('2024-12-01'),
    endDate: new Date('2025-01-31'),
    status: 'preparing',
    jobCount: 2,
    applicationCount: 0,
    description: '面向医学工程学院2025届毕业生的生物医药专场招聘活动。',
    createdAt: new Date('2024-11-01'),
    updatedAt: new Date('2024-11-01'),
  },"""

pattern = r"(export const employmentProjects: EmploymentProject\[\] = \[.*?)(\n\])"
match = re.search(pattern, content, re.DOTALL)
if match:
    insert_pos = match.start(2)
    content = content[:insert_pos] + projects_extra + content[insert_pos:]

with open('lib/mock-data.ts', 'w', encoding='utf-8') as f:
    f.write(content)

print("Batch 3 done: jobs +9, studentProfiles +9, jobApplications +15, employmentProjects +4")
